(function(){
  'use strict';
  const PB = window.POKEBATTLE || (window.POKEBATTLE = {});
  const FIX = PB.phase2CleanV8 = PB.phase2CleanV8 || { active:false, roomId:null, roomRef:null, room:null, started:false, resolving:false, sent:false, lastTurn:0, lastStabilize:0 };
  const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const now = () => Date.now();
  const core = () => PB.core;
  const ui = () => PB.ui;
  const online = () => PB.online || {};
  const db = () => online().db || null;
  const uid = () => online().uid || null;
  const slot = () => online().selectedSlot || 'char1';
  const myKey = () => uid() ? `${uid()}_${slot()}` : '';
  const player = () => core()?.getPlayer?.('p1') || core()?.getActivePlayer?.() || null;
  const char = () => online().selectedCharacter || null;
  const toast = m => ui()?.showToast?.(m);
  const meta = {
    normal:['일반혈통','#bfc5cf','#07111e'],
    elite:['우수혈통','#55c9ff','#07111e'],
    ancient:['고대혈통','#ffd84f','#171000'],
    mew:['뮤의 후손','#b66cff','#07111e']
  };
  const spriteMap = {
    '아보크':'Arbok.png','터검니':'Axew.png','거북왕':'Blastoise.png','번치코':'Blaziken.png','꼬몽울':'Budew.png','샤프니아':'Carvanha.png','리자몽':'Charizard.png','파이리':'Charmander.png','리자드':'Charmeleon.png','불꽃숭이':'Chimchar.png','에이스번':'Cinderace.png','영치코':'Combusken.png','두개도스':'Cranidos.png','크로뱃':'Crobat.png','달막화':'Darumaka.png','쌍검자비':'Dewott.png','망나뇽':'Dragonite.png','누겔레온':'Drizzile.png','아보':'Ekans.png','염무왕':'Emboar.png','액슨도':'Fraxure.png','한카리아스':'Garchomp.png','골뱃':'Golbat.png','흥나숭':'Grookey.png','수풀부기':'Grotle.png','나무돌이':'Grovyle.png','초염몽':'Infernape.png','인텔리레온':'Inteleon.png','킬리아':'Kirlia.png','늪짱이':'Marshtomp.png','단데기':'Metapod.png','밀로틱':'Milotic.png','파이숭이':'Monferno.png','물짱이':'Mudkip.png','니드퀸':'nidg.png','니드런♀':'nidg.png','니드리나':'nidna.png','니드킹':'nidno.png','니드리노':'nidno.png','니드런♂':'nidno.png','수댕이':'Oshawott.png','차오꿀':'Pignite.png','피카츄':'Pikachu.png','래비풋':'Raboot.png','레트라':'Raticate.png','꼬렛':'Rattata.png','고릴타':'Rillaboom.png','로젤리아':'Roselia.png','대검귀':'Samurott.png','나무킹':'Sceptile.png','염버니':'Scorbunny.png','샤로다':'Serperior.png','샤비':'Servine.png','주리비얀':'Snivy.png','눈꼬마':'Snorunt.png','울머기':'Sobble.png','화강돌':'Spiritomb.png','꼬부기':'Squirtle.png','파비코':'Swablu.png','파비꼬':'Swablu.png','대짱이':'Swampert.png','뚜꾸리':'Tepig.png','채키몽':'Thwackey.png','아차모':'Torchic.png','토대부기':'Torterra.png','나무지기':'Treecko.png','모부기':'Turtwig.png','어니부기':'Wartortle.png','주뱃':'Zubat.png','주벳':'Zubat.png'
  };
  function bkey(v){ const s=String(v||''); if(s.includes('뮤')||s==='mew') return 'mew'; if(s.includes('고대')||s==='ancient') return 'ancient'; if(s.includes('우수')||s==='elite') return 'elite'; return 'normal'; }
  function monName(p){ return p?.currentName || p?.name || p?.base?.nameKo || p?.nameKo || '포켓몬'; }
  function baseById(id){ return core()?.state?.pokemonById?.get?.(Number(id)); }
  function allOwned(){ const p=player(); return [...(p?.squad||[]), ...(p?.reserve||[])].filter(Boolean); }
  function applySprites(){
    const all = core()?.state?.allPokemon || [];
    all.forEach(b=>{ const fn=spriteMap[b?.nameKo]; if(fn){ const src=`starter-sprites/${fn}`; b.image=src; b.sprite=src; b.asset=src; b.mediaNameKo=b.nameKo; }});
  }
  function injectCss(){
    if(document.getElementById('phase2-clean-v8-style')) return;
    const st=document.createElement('style'); st.id='phase2-clean-v8-style'; st.textContent = `
      body,body.theme-basic,body.theme-dark{background:#050914!important;color:#fff!important;}
      body.theme-basic .app-root,body.theme-basic .screen{background:inherit!important;color:#fff!important;}
      .settings-choice[data-theme-mode="basic"],button[data-theme-mode="basic"]{display:none!important;}
      .settings-row:has([data-theme-mode="basic"])::before{content:'다크모드 적용 중';color:#fff;font-weight:900;}
      .bloodline-tip-card-v3{display:none!important;height:0!important;margin:0!important;padding:0!important;overflow:hidden!important;}
      .bloodline-text-v3,.battle-bloodline-v3,.p2-blood,.rt-blood,.blood-block,.v7-blood-block,.p2fp-blood-fixed,.fix3-blood-chip,.v8-blood-badge{display:inline-flex!important;align-items:center!important;justify-content:center!important;border-radius:999px!important;padding:3px 8px!important;min-height:18px!important;line-height:1.1!important;font-size:10px!important;font-weight:1000!important;text-shadow:none!important;box-shadow:none!important;filter:none!important;animation:none!important;transition:none!important;background-image:none!important;border:1px solid rgba(255,255,255,.6)!important;white-space:nowrap!important;}
      .pokemon-card,.reserve-chip,[data-select-uid]{position:relative!important;}
      [data-select-uid] .bloodline-text-v3,[data-select-uid] .v8-blood-badge{position:absolute!important;right:10px!important;bottom:8px!important;z-index:8!important;}
      .battle-status-card .battle-bloodline-v3{position:absolute!important;right:8px!important;bottom:6px!important;z-index:8!important;}
      .stat-value.is-best,.stat-value.v8-best-stat,.pokemon-stat-value.is-best,.squad-stat-value.is-best,[data-best-stat="1"]{color:#ff8a00!important;-webkit-text-fill-color:#ff8a00!important;background:transparent!important;border:0!important;outline:0!important;box-shadow:none!important;text-shadow:none!important;animation:none!important;transition:none!important;font-weight:1000!important;}
      .pokemon-card,.reserve-chip{animation:none!important;transition:transform .12s ease, border-color .12s ease!important;}
      .pokemon-card:active,.reserve-chip:active{transform:none!important;}
      .stable-rest-shell,.v8-rest-shell{position:relative!important;height:calc(100dvh - 150px)!important;min-height:480px!important;background:transparent!important;border:0!important;box-shadow:none!important;margin:0!important;padding:0!important;overflow:hidden!important;}
      .fix3-rest-grass,.rest-grass,.rest-area-hotfix .rest-grass,.rest-area .rest-grass{display:none!important;}
      .v8-rest-exit{position:absolute!important;right:12px!important;top:12px!important;z-index:12!important;border:1px solid rgba(255,255,255,.35)!important;border-radius:999px!important;background:rgba(0,0,0,.55)!important;color:#fff!important;padding:9px 14px!important;font-weight:1000!important;}
      .v8-rest-main{position:absolute!important;right:17%!important;bottom:18%!important;width:86px!important;height:86px!important;z-index:8!important;display:flex!important;align-items:center!important;justify-content:center!important;cursor:pointer!important;touch-action:manipulation!important;}
      .v8-rest-main img{max-width:86px!important;max-height:86px!important;object-fit:contain!important;filter:drop-shadow(0 6px 16px rgba(0,0,0,.35))!important;animation:none!important;transition:none!important;}
      .v8-rest-main.jump{animation:v8RestJump 1s ease-in-out 1!important;}
      @keyframes v8RestJump{0%,100%{transform:translateY(0)}35%{transform:translateY(-26px)}70%{transform:translateY(4px)}}
      .v8-pvp-wait{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;width:100%;min-height:116px;background:rgba(255,255,255,.92);border-radius:18px;color:#06101f!important;font-weight:1000;text-align:center;padding:16px;}
      .v8-pvp-wait button{border:0;border-radius:999px;background:#111827;color:#fff!important;font-weight:1000;padding:9px 14px;}
      #battle-action-grid .action-button,#battle-action-grid .action-button span,#battle-action-grid .action-button div:not(.type-badge),.battle-move-button,.battle-move-button *:not(.type-badge):not(.battle-category-pill){color:#050b18!important;-webkit-text-fill-color:#050b18!important;text-shadow:none!important;}
      .v8-endstats{width:100%;background:rgba(255,255,255,.94);color:#06101f!important;border-radius:18px;padding:12px}.v8-endstats *{color:#06101f!important}.v8-endstats table{width:100%;border-collapse:collapse}.v8-endstats td,.v8-endstats th{padding:5px;border-bottom:1px solid rgba(0,0,0,.12);text-align:left}
    `; document.head.appendChild(st);
  }
  function setBlood(el, val){ const k=bkey(val); const m=meta[k]||meta.normal; el.textContent=m[0]; el.dataset.bloodline=k; el.style.setProperty('background',m[1],'important'); el.style.setProperty('background-color',m[1],'important'); el.style.setProperty('color',m[2],'important'); el.style.setProperty('-webkit-text-fill-color',m[2],'important'); el.style.setProperty('box-shadow','none','important'); el.style.setProperty('text-shadow','none','important'); el.style.setProperty('animation','none','important'); el.style.setProperty('transition','none','important'); }
  function removeTopBlood(){ const root=document.getElementById('content-area'); if(!root) return; [...root.children].forEach(ch=>{ const t=(ch.textContent||'').replace(/\s+/g,' ').trim(); if((t.includes('혈통')&&t.includes('랜덤 혈통')&&!ch.querySelector('[data-select-uid]'))||ch.classList.contains('bloodline-tip-card-v3')) ch.remove(); }); }
  function stabilizeBlood(){ const map=new Map(allOwned().filter(m=>m.uid).map(m=>[m.uid,m])); const keep=new Set(); document.querySelectorAll('[data-select-uid]').forEach(card=>{ const mon=map.get(card.dataset.selectUid); if(!mon) return; let badges=[...card.querySelectorAll('.bloodline-text-v3,.blood-block,.v7-blood-block,.p2fp-blood-fixed,.fix3-blood-chip,.v8-blood-badge')]; badges.slice(1).forEach(b=>b.remove()); let b=badges[0]; if(!b){ b=document.createElement('span'); b.className='v8-blood-badge'; card.appendChild(b); } b.classList.add('v8-blood-badge'); setBlood(b, mon.bloodline || 'normal'); keep.add(b); }); document.querySelectorAll('.battle-status-card').forEach(card=>{ const b=card.querySelector('.battle-bloodline-v3'); if(!b) return; const snap=PB.battleEngine?.getSnapshot?.(); const local = card.classList.contains('ally'); let mon = local ? snap?.ally : snap?.enemy; if(local && mon?.uid){ const own=map.get(mon.uid); if(own?.bloodline) mon=own; } setBlood(b, mon?.bloodline || b.dataset.bloodline || b.textContent); keep.add(b); }); document.querySelectorAll('.p2-blood,.rt-blood').forEach(b=>{ setBlood(b,b.dataset.bloodline||b.textContent); keep.add(b); }); document.querySelectorAll('.bloodline-text-v3,.battle-bloodline-v3,.p2-blood,.rt-blood,.blood-block,.v7-blood-block,.p2fp-blood-fixed,.fix3-blood-chip,.v8-blood-badge').forEach(b=>{ if(!keep.has(b) && !b.closest('[data-select-uid],.battle-status-card,.p2-player-row,.rt-mon-card,.modal-card,.p2-card')) b.remove(); }); }
  function stabilizeStats(){ const p=player(); const team=(p?.squad||[]).slice(0,3); const keys=['hp','attack','defense','spAttack','spDefense','speed']; document.querySelectorAll('.stat-value.is-best,.pokemon-stat-value.is-best,.squad-stat-value.is-best,[data-best-stat="1"]').forEach(el=>{ el.classList.add('v8-best-stat'); el.style.setProperty('color','#ff8a00','important'); el.style.setProperty('-webkit-text-fill-color','#ff8a00','important'); }); document.querySelectorAll('[data-select-uid]').forEach(card=>{ const mon=team.find(m=>m.uid===card.dataset.selectUid); if(!mon) return; const vals=keys.map(k=>Number(mon.stats?.[k]||mon[k]||0)); const max=Math.max(...vals); [...card.querySelectorAll('.stat-value,.pokemon-stat-value,.squad-stat-value')].forEach(n=>{ const v=parseInt((n.textContent||'').replace(/[^0-9]/g,''),10); if(v===max){ n.classList.add('v8-best-stat'); n.style.setProperty('color','#ff8a00','important'); n.style.setProperty('-webkit-text-fill-color','#ff8a00','important'); } }); }); }
  function stabilizeUi(){ document.body.classList.remove('theme-basic'); document.body.classList.add('theme-dark'); removeTopBlood(); stabilizeBlood(); stabilizeStats(); applySprites(); }
  function wrapRender(){ if(ui()?.__v8CleanRender) return; const old=ui().renderAll; ui().__v8CleanRender=true; ui().renderAll=function(){ const r=old.apply(this,arguments); requestAnimationFrame(stabilizeUi); return r; }; }
  function renderRest(){ const shell=document.querySelector('.p2-online-shell')||document.getElementById('content-area')||document.querySelector('.content-scroll'); if(!shell) return; const tabs=document.querySelector('.p2-tabs')?.outerHTML || document.querySelector('.online-tab-row')?.outerHTML || ''; const m=(player()?.squad||[])[0]; const src=m?.base?.image||m?.base?.sprite||m?.base?.asset||''; shell.innerHTML=tabs+`<section class="v8-rest-shell"><button type="button" class="v8-rest-exit" data-v8-rest-exit="1">나가기</button><div class="v8-rest-main" data-v8-rest-main="1">${src?`<img src="${esc(src)}" alt="${esc(monName(m))}">`:`<span>${esc(String(monName(m)).slice(0,1))}</span>`}</div></section>`; }
  function compact(p){ if(!p?.base) return null; return {uid:p.uid||`p_${p.base.id}_${Math.random().toString(36).slice(2,8)}`,sourceUid:p.sourceUid||p.uid||'',baseId:Number(p.base.id||0),name:monName(p),level:Math.min(100,Number(p.level||5)),maxHp:Number(p.maxHp||p.stats?.hp||1),currentHp:Math.max(0,Number(p.currentHp??p.maxHp??1)),status:p.status||'',bloodline:p.bloodline||'normal',enhanceLevel:Number(p.enhanceLevel||0),statStages:{...(p.statStages||{})},volatile:{...(p.volatile||{})},stats:{...(p.stats||{})},heldItems:(p.heldItems||(p.heldItem?[p.heldItem]:[])).map(it=>({...(it||{})})),moves:(p.moves||[]).slice(0,4).map(m=>({...m,currentPP:Number(m.currentPP??m.pp??m.maxPP??10),maxPP:Number(m.maxPP??m.pp??10)}))}; }
  function inflate(d){ const b=baseById(d?.baseId), c=core(); if(!b||!c?.createRuntimePokemon) return null; const p=c.createRuntimePokemon(b,Math.min(100,Number(d.level||5))); p.uid=d.uid||p.uid; p.sourceUid=d.sourceUid||p.sourceUid; p.currentName=d.name||p.currentName; p.bloodline=d.bloodline||p.bloodline||'normal'; p.enhanceLevel=Number(d.enhanceLevel||0); try{c.recalculateRuntimeStats?.(p,{fullHeal:true});}catch(e){} if(d.stats)p.stats={...(p.stats||{}),...d.stats}; p.maxHp=Number(d.maxHp||p.maxHp||1); p.currentHp=Math.max(0,Math.min(p.maxHp,Number(d.currentHp??p.maxHp))); p.status=d.status||''; p.statStages={...(d.statStages||{})}; p.volatile={...(d.volatile||{})}; p.heldItems=Array.isArray(d.heldItems)?d.heldItems.map(it=>({...it})):[]; p.heldItem=p.heldItems[0]||null; if(Array.isArray(d.moves)&&d.moves.length)p.moves=d.moves.slice(0,4).map(m=>({...m})); return p; }
  function localTeam(){ return (player()?.squad||[]).slice(0,3).map(compact).filter(Boolean); }
  function pubTeam(pub){ return (pub?.battleTeam||pub?.squad||[]).slice(0,3).map(x=>inflate(x)).filter(Boolean).map(compact); }
  function isHost(room){ return myKey() && room?.challengerKey===myKey(); }
  function isGuest(room){ return myKey() && room?.targetKey===myKey(); }
  function otherKey(room){ return isHost(room)?room.targetKey:room.challengerKey; }
  function alive(list){ return (list||[]).some(p=>Number(p?.currentHp||0)>0); }
  function firstAlive(list){ const i=(list||[]).findIndex(p=>Number(p?.currentHp||0)>0); return i<0?0:i; }
  function showWait(msg){ const c=core(); if(c?.state){ c.state.currentScreen='battle'; } if(!document.getElementById('battle-screen') || document.getElementById('battle-screen').classList.contains('hidden')) ui()?.renderAll?.(); const grid=document.getElementById('battle-action-grid'); if(grid) grid.innerHTML=`<div class="v8-pvp-wait"><div>${esc(msg)}</div><button type="button" data-v8-pvp-exit="1">나가기</button></div>`; const log=document.getElementById('battle-log'); if(log) log.textContent=msg; }
  function stopPvp(){ if(FIX.roomRef){ try{FIX.roomRef.off();}catch(e){} } FIX.active=false; FIX.roomId=null; FIX.roomRef=null; FIX.room=null; FIX.started=false; FIX.resolving=false; FIX.sent=false; }
  async function exitPvp(){ const d=db(); if(FIX.roomId&&d){ try{ await d.ref(`battleRooms/${FIX.roomId}`).update({status:'cancelled',cancelledBy:myKey(),updatedAt:now()}); }catch(e){} } stopPvp(); core().state.currentScreen='lobby'; ui()?.renderAll?.(); }
  function makeState(room){ const h=isHost(room)?localTeam():pubTeam(room.challenger); const g=isGuest(room)?localTeam():pubTeam(room.target); return {version:8,phase:'select',turn:1,hostKey:room.challengerKey,guestKey:room.targetKey,actions:null,lastResult:null,teams:{[room.challengerKey]:h,[room.targetKey]:g},createdAt:now(),updatedAt:now()}; }
  function syncFromEngine(){ try{return PB.battleEngine?.exportPvpSyncState?.();}catch(e){return null;} }
  function auto(sync){ if(!sync) return sync; const fix=(team,idx)=>{idx=Number(idx||0); return team?.[idx]&&Number(team[idx].currentHp||0)>0?idx:firstAlive(team);}; sync.allyIndex=fix(sync.playerTeam,sync.allyIndex); sync.enemyIndex=fix(sync.opponentTeam,sync.enemyIndex); sync.completed=!(alive(sync.playerTeam)&&alive(sync.opponentTeam)); return sync; }
  function startLocal(room){ if(FIX.started) return; const p=room.pvpV8; if(!p?.teams) return; const mine=isHost(room)?p.teams[room.challengerKey]:p.teams[room.targetKey]; const opp=isHost(room)?p.teams[room.targetKey]:p.teams[room.challengerKey]; const myT=(mine||[]).map(inflate).filter(Boolean); const opT=(opp||[]).map(inflate).filter(Boolean); if(!myT.length||!opT.length){ toast('배틀 팀을 불러오지 못했습니다.'); return; } try{ if(PB.phase2FinalStability) PB.phase2FinalStability.active=false; if(PB.phase2ContentFix3) PB.phase2ContentFix3.active=false; if(PB.phase2PvpRestStable) PB.phase2PvpRestStable.active=false; }catch(e){} FIX.started=true; FIX.lastTurn=0; FIX.sent=false; PB.battleEngine?.startBattle?.({playerId:'p1',opponentId:'online_pvp_enemy',playerName:char()?.name||player()?.name||'나',opponentName:(isHost(room)?room.target:room.challenger)?.characterName||'상대 플레이어',playerTeam:myT,opponentTeam:opT,mode:'online_pvp',isDuo:true,skipLevelReward:true,theme:'city',onComplete:(payload)=>{ renderStats(payload); return true; }}); setTimeout(()=>PB.battleEngine?.clearPvpWaiting?.(),80); }
  function renderStats(payload){ const stats=payload?.stats || syncFromEngine()?.stats || {}; const rows=Object.values(stats).map(s=>`<tr><td>${esc(s.name||s.pokemonName||'포켓몬')}</td><td>${Number(s.damageDealt||0)}</td><td>${Number(s.survivedDamage||s.damageTaken||0)}</td></tr>`).join('') || '<tr><td colspan="3">통계 없음</td></tr>'; const grid=document.getElementById('battle-action-grid'); if(grid) grid.innerHTML=`<div class="v8-endstats"><h3>배틀 통계</h3><table><thead><tr><th>포켓몬</th><th>딜량</th><th>버틴피해</th></tr></thead><tbody>${rows}</tbody></table><button class="action-button" data-v8-end-exit="1"><span class="action-title">나가기</span></button></div>`; }
  async function enterRoom(id){ /* delegate-to-v10 */ if(window.PB_REALTIME_PVP?.__unifiedV10 && !window.__ALLOW_OLD_PVP){ return window.PB_REALTIME_PVP.enterRoom(id); } const d=db(); if(!d||!uid()){ toast('로그인 후 이용하세요.'); return; } stopPvp(); const ref=d.ref(`battleRooms/${id}`); const snap=await ref.get(); const r={id,...(snap.val()||{})}; if(!r.id || !(isHost(r)||isGuest(r))){ toast('참가 가능한 방이 아닙니다.'); return; } FIX.active=true; FIX.roomId=id; FIX.roomRef=ref; FIX.room=r; FIX.started=false; FIX.lastTurn=0; FIX.sent=false; showWait('상대방 대기 중...'); await ref.update({status:'readying',[`v8Ready/${myKey()}`]:true,updatedAt:now()}).catch(e=>console.warn(e)); ref.on('value', async sn=>{ const room={id,...(sn.val()||{})}; if(!FIX.active||room.id!==FIX.roomId) return; FIX.room=room; await onRoom(room); }); }
  async function onRoom(room){ if(room.status==='cancelled'){ stopPvp(); toast('배틀방이 종료되었습니다.'); core().state.currentScreen='lobby'; ui()?.renderAll?.(); return; } const rh=!!room.v8Ready?.[room.challengerKey], rg=!!room.v8Ready?.[room.targetKey]; if(!(rh&&rg)){ showWait('상대방 대기 중...'); return; } if(!room.pvpV8 && isHost(room)){ await db().ref(`battleRooms/${room.id}`).transaction(cur=>{ if(!cur) return cur; if(!cur.pvpV8) cur.pvpV8=makeState({id:room.id,...cur}); cur.status='inProgress'; cur.updatedAt=now(); return cur; }); return; } if(!room.pvpV8){ showWait('배틀 준비 중...'); return; } startLocal(room); const p=room.pvpV8; const lr=p.lastResult; if(lr && Number(lr.turn||0)>FIX.lastTurn){ FIX.lastTurn=Number(lr.turn||0); FIX.sent=false; try{ PB.battleEngine?.importPvpSyncState?.(auto(lr.syncState),{reverse:!isHost(room)}); }catch(e){ console.warn('PVP 결과 반영 실패',e); } setTimeout(()=>PB.battleEngine?.clearPvpWaiting?.(),100); if(room.status==='completed'||p.phase==='completed'){ renderStats({stats:lr.syncState?.stats||{}}); } } if(isHost(room) && !FIX.resolving && p.phase==='select' && p.actions?.[room.challengerKey] && p.actions?.[room.targetKey]){ FIX.resolving=true; try{ await resolveHost(room); }catch(e){ console.warn('v8 pvp resolve failed',e); await recover(room); } FIX.resolving=false; } const mine=p.actions?.[myKey()], other=p.actions?.[otherKey(room)]; if(mine&&!other) showWait('상대방이 선택하는 중'); else if(!mine && !other && FIX.started) setTimeout(()=>PB.battleEngine?.clearPvpWaiting?.(),60); }
  async function resolveHost(room){ const p=room.pvpV8, h=room.challengerKey, g=room.targetKey; let sync; try{ sync=await PB.battleEngine?.resolvePvpSyncedTurn?.(p.actions[h],p.actions[g]); }catch(e){ console.warn(e); sync=syncFromEngine(); } sync=auto(sync||{}); const hAlive=alive(sync.playerTeam), gAlive=alive(sync.opponentTeam); const u={}; u[`battleRooms/${room.id}/pvpV8/actions`]=null; u[`battleRooms/${room.id}/pvpV8/lastResult`]={turn:Number(p.turn||1),syncState:sync,createdAt:now()}; u[`battleRooms/${room.id}/pvpV8/updatedAt`]=now(); if(!hAlive||!gAlive||sync.completed){ const winnerKey=hAlive&&!gAlive?h:gAlive&&!hAlive?g:(hAlive?h:g); u[`battleRooms/${room.id}/status`]='completed'; u[`battleRooms/${room.id}/result`]={winnerKey,winnerName:(winnerKey===h?room.challenger:room.target)?.characterName||'',completedAt:now(),sameUi:true}; u[`battleRooms/${room.id}/pvpV8/phase`]='completed'; if(room.mode==='champion'&&winnerKey===h) u['competitive/champion']={...room.challenger,championSince:now(),reason:'sameUiChallengeWin'}; } else { u[`battleRooms/${room.id}/pvpV8/turn`]=Number(p.turn||1)+1; u[`battleRooms/${room.id}/pvpV8/phase`]='select'; } await db().ref().update(u); }
  async function recover(room){ const sync=auto(syncFromEngine()||{playerTeam:room.pvpV8?.teams?.[room.challengerKey]||[],opponentTeam:room.pvpV8?.teams?.[room.targetKey]||[],log:['턴을 복구했습니다.'],completed:false}); await db().ref().update({[`battleRooms/${room.id}/pvpV8/actions`]:null,[`battleRooms/${room.id}/pvpV8/lastResult`]:{turn:Number(room.pvpV8?.turn||1),syncState:sync,createdAt:now()},[`battleRooms/${room.id}/pvpV8/turn`]:Number(room.pvpV8?.turn||1)+1,[`battleRooms/${room.id}/pvpV8/phase`]:'select',[`battleRooms/${room.id}/pvpV8/updatedAt`]:now()}); }
  async function submit(action){ if(!FIX.active||!FIX.roomId||!db()||FIX.sent) return; FIX.sent=true; showWait('상대방이 선택하는 중'); await db().ref(`battleRooms/${FIX.roomId}/pvpV8/actions/${myKey()}`).set({...action,at:now()}); }
  function bind(){
    window.addEventListener('click', async e=>{
      const start=e.target.closest?.('[data-p2-room-start]'); if(start){ e.preventDefault(); e.stopImmediatePropagation(); await enterRoom(start.dataset.p2RoomStart); return; }
      const rest=e.target.closest?.('[data-p2-tab="rest"]'); if(rest){ e.preventDefault(); e.stopImmediatePropagation(); if(PB.phase2Online) PB.phase2Online.tab='rest'; renderRest(); return; }
      if(e.target.closest?.('[data-v8-rest-exit]')){ e.preventDefault(); e.stopImmediatePropagation(); if(PB.phase2Online) PB.phase2Online.tab='ranked'; ui()?.renderAll?.(); return; }
      const rp=e.target.closest?.('[data-v8-rest-main]'); if(rp){ e.preventDefault(); e.stopImmediatePropagation(); rp.classList.remove('jump'); void rp.offsetWidth; rp.classList.add('jump'); return; }
      if(e.target.closest?.('[data-v8-pvp-exit]')){ e.preventDefault(); e.stopImmediatePropagation(); await exitPvp(); return; }
      if(e.target.closest?.('[data-v8-end-exit],[data-stable-end-exit],[data-fix3-end-exit],[data-battle-exit-lobby],[data-final-exit-lobby],[data-content-v2-exit],[data-hotfix-exit-lobby]')){ e.preventDefault(); e.stopImmediatePropagation(); stopPvp(); if(PB.phase2ContentV2){PB.phase2ContentV2.endLocked=false;PB.phase2ContentV2.allowExit=true;} if(PB.phase2ContentHotfix){PB.phase2ContentHotfix.endLocked=false;} if(PB.phase2FinalStability){PB.phase2FinalStability.endShowing=false;PB.phase2FinalStability.allowLobbyUntil=Date.now()+3000;} core().state.currentScreen='lobby'; ui()?.renderAll?.(); return; }
      if(!FIX.active || !FIX.started) return;
      const act=e.target.closest?.('[data-battle-action]'); if(act){ const a=act.dataset.battleAction; if(['fight','bag','pokemon','info'].includes(a)){ e.preventDefault(); e.stopImmediatePropagation(); if(!FIX.sent){ PB.battleEngine?.clearPvpWaiting?.(); PB.battleEngine?.handleRootAction?.(a); } return; } }
      const root=e.target.closest?.('[data-battle-root]'); if(root){ e.preventDefault(); e.stopImmediatePropagation(); if(!FIX.sent) PB.battleEngine?.setMenu?.('root'); return; }
      const mv=e.target.closest?.('[data-battle-move]'); if(mv){ e.preventDefault(); e.stopImmediatePropagation(); await submit({type:'move',index:Number(mv.dataset.battleMove||0)}); return; }
      const sw=e.target.closest?.('[data-battle-switch]'); if(sw){ e.preventDefault(); e.stopImmediatePropagation(); await submit({type:'switch',index:Number(sw.dataset.battleSwitch||0)}); return; }
      const item=e.target.closest?.('[data-battle-item]'); if(item){ e.preventDefault(); e.stopImmediatePropagation(); const id=item.dataset.battleItem; if(['pp_aid','pp_aide','revive_shard'].includes(id)){ if(!FIX.sent) PB.battleEngine?.handleBagSelect?.(id); } else await submit({type:'item',itemId:id}); return; }
      const im=e.target.closest?.('[data-battle-item-move]'); if(im){ e.preventDefault(); e.stopImmediatePropagation(); await submit({type:'item',itemId:'pp_aid',moveIndex:Number(im.dataset.battleItemMove||0)}); return; }
      const ip=e.target.closest?.('[data-battle-item-pokemon]'); if(ip){ e.preventDefault(); e.stopImmediatePropagation(); await submit({type:'item',itemId:'revive_shard',targetIndex:Number(ip.dataset.battleItemPokemon||0)}); return; }
    }, true);
  }
  function init(){ injectCss(); applySprites(); if(core()?.state?.settings) core().state.settings.theme='dark'; document.body.classList.remove('theme-basic'); document.body.classList.add('theme-dark'); wrapRender(); bind(); window.PB_REALTIME_PVP = { enterRoom, close:stopPvp, __v8:true }; window.PB_STABLE_PVP = { enterRoom, close:stopPvp, renderRest, __v8:true }; setTimeout(stabilizeUi,120); }
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',init); else init();
})();
