(function(){
  'use strict';
  const PB = window.POKEBATTLE || (window.POKEBATTLE = {});
  const FIX = PB.phase2ContentHotfix = PB.phase2ContentHotfix || { endLocked:false, endPayload:null, restTimer:null, rankingTier:'monster', patched:false };
  const esc = (v)=>String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const norm = (v)=>String(v||'').toLowerCase().replace(/[^a-z0-9_가-힣]/g,'');
  function core(){return PB.core;} function ui(){return PB.ui;} function online(){return PB.online||{};} function player(){return core()?.getPlayer?.('p1')||core()?.getActivePlayer?.()||null;} function toast(m){ui()?.showToast?.(m);} 
  function currentMain(){return (player()?.squad||[])[0]||null;} function pName(p){return p?.currentName||p?.name||p?.base?.nameKo||p?.nameKo||'포켓몬';}
  const BL={normal:['일반혈통','#bfc5cf','#06101f'],elite:['우수혈통','#46b9ff','#06101f'],ancient:['고대혈통','#ffd550','#171100'],mew:['뮤의 후손','#b66bff','#06101f']};
  function bkey(v){const s=String(v||'normal'); if(s.includes('뮤')||s==='mew'||s==='mew_descendant'||s==='purple')return'mew'; if(s.includes('고대')||s==='ancient'||s==='gold')return'ancient'; if(s.includes('우수')||s==='elite'||s==='superior'||s==='blue'||s==='great')return'elite'; return'normal';}
  function bloodStyle(el){const k=bkey(el.textContent||el.dataset.bloodline||''); const [txt,bg,fg]=BL[k]; el.textContent=txt; el.style.setProperty('display','inline-flex','important'); el.style.setProperty('align-items','center','important'); el.style.setProperty('justify-content','center','important'); el.style.setProperty('padding','3px 8px','important'); el.style.setProperty('border-radius','999px','important'); el.style.setProperty('background',bg,'important'); el.style.setProperty('color',fg,'important'); el.style.setProperty('-webkit-text-fill-color',fg,'important'); el.style.setProperty('font-weight','900','important'); el.style.setProperty('box-shadow','none','important'); el.style.setProperty('text-shadow','none','important'); el.style.setProperty('animation','none','important'); el.style.setProperty('transition','none','important');}

  function installCss(){ if(document.getElementById('content-hotfix-style'))return; const st=document.createElement('style'); st.id='content-hotfix-style'; st.textContent=`
    #modal-root:empty{display:none!important;pointer-events:none!important}#modal-root:not(:empty){pointer-events:auto!important}
    .stat-value.is-best,.pokemon-card .stat-value.is-best,.squad-grid .stat-value.is-best{color:#ff922e!important;-webkit-text-fill-color:#ff922e!important;border:0!important;box-shadow:none!important;text-shadow:none!important;background:transparent!important;animation:none!important;transition:none!important;}
    .pokemon-card .stat-box .stat-value.is-best{color:#ff922e!important;-webkit-text-fill-color:#ff922e!important;}
    .bloodline-text-v3,.battle-bloodline-v3,.p2-blood,.rt-blood,.blood-block,.v7-blood-block,.p2fp-blood-fixed{box-shadow:none!important;text-shadow:none!important;animation:none!important;transition:none!important;}
    .p2-rank-tier-tabs{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0 12px}.p2-rank-tier-tabs button{border:1px solid rgba(126,216,255,.38);border-radius:999px;padding:9px 12px;background:rgba(6,14,28,.48);color:#fff;font-weight:900}.p2-rank-tier-tabs button.active{background:linear-gradient(135deg,#1b91ff,#48defe);color:#04111d;}
    .rest-area-hotfix{position:relative;min-height:calc(100dvh - 145px);height:calc(100dvh - 145px);border-radius:26px;overflow:hidden;background:linear-gradient(180deg,rgba(0,20,12,.10),rgba(0,0,0,.30)),url('pokebackground.png') center/cover no-repeat}.rest-area-hotfix .rest-exit{position:absolute;right:12px;top:12px;z-index:6;border:1px solid rgba(255,255,255,.35);border-radius:999px;background:rgba(0,0,0,.58);color:#fff;padding:9px 14px;font-weight:1000}.rest-area-hotfix .rest-grass{position:absolute;right:8px;bottom:18px;width:min(46vw,250px);z-index:2}.rest-area-hotfix .rest-mon img,.rest-area-hotfix .rest-mon span{position:absolute;z-index:3;max-width:84px;max-height:84px;animation:hotRestWiggle 2.1s ease-in-out forwards;transform-origin:50% 100%}.rest-area-hotfix .rest-mon span{width:64px;height:64px;border-radius:50%;display:flex;align-items:center;justify-content:center;background:#ffd84f;color:#06101f;font-weight:1000}@keyframes hotRestWiggle{0%{opacity:0;transform:translateY(10px) rotate(0)}18%{opacity:1;transform:translateY(0) rotate(-28deg)}40%{transform:rotate(28deg)}64%{transform:rotate(-20deg)}100%{opacity:0;transform:translateY(8px) rotate(0)}}
    .safe-shop-card h3,.safe-shop-card .shop-name{color:#fff!important;-webkit-text-fill-color:#fff!important}.safe-shop-price{background:#ffd84f!important;color:#07101e!important;-webkit-text-fill-color:#07101e!important;border-radius:999px;padding:5px 10px;font-weight:1000}.safe-shop-modal{background:rgba(5,12,24,.88)!important;color:#fff!important}.safe-shop-modal *{box-sizing:border-box}.safe-shop-modal .shop-item-meta{color:#d9e8ff!important}.safe-shop-grid{display:grid;gap:10px;max-height:62vh;overflow:auto;padding-right:2px}.safe-shop-card{border:1px solid rgba(126,216,255,.22);border-radius:16px;background:rgba(255,255,255,.10);padding:12px;text-align:left}.safe-shop-card p{color:#e9f4ff!important}.safe-shop-row{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.safe-shop-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:8px}.safe-shop-actions button{border-radius:999px;padding:6px 10px;border:1px solid rgba(255,255,255,.25);background:rgba(255,255,255,.12);color:#fff;font-weight:900}.safe-shop-actions .buy{background:linear-gradient(135deg,#1b91ff,#52e2ff);color:#04111d}.v2-endstats,.p2fp-endstats,.hotfix-endstats{width:100%;background:rgba(255,255,255,.94);color:#06101f;border-radius:18px;padding:12px}.v2-endstats *,.p2fp-endstats *,.hotfix-endstats *{color:#06101f!important}.hotfix-endstats table{width:100%;border-collapse:collapse}.hotfix-endstats th,.hotfix-endstats td{padding:5px;border-bottom:1px solid rgba(0,0,0,.12);text-align:left}.pvp-ready-wait .hotfix-exit,.pvp-ready-wait.big .hotfix-exit{margin-top:8px}.online-tab-row [data-p2-tab="rest"]{display:inline-flex!important}
  `; document.head.appendChild(st); }

  function renderEndStats(payload){
    const p=payload||FIX.endPayload||{}; const stats=p.stats || PB.battleEngine?.getSnapshot?.()?.stats || {};
    const rows=Object.values(stats).map(s=>`<tr><td>${esc(s.name||s.pokemonName||'포켓몬')}</td><td>${Number(s.damageDealt||0)}</td><td>${Number(s.survivedDamage||s.damageTaken||0)}</td></tr>`).join('') || '<tr><td colspan="3">통계 없음</td></tr>';
    const html=`<div class="hotfix-endstats"><h3>배틀 통계</h3><table><thead><tr><th>포켓몬</th><th>딜량</th><th>버틴피해</th></tr></thead><tbody>${rows}</tbody></table><button class="action-button" data-hotfix-exit-lobby="1"><span class="action-title">나가기</span><span class="action-sub">로비로 돌아갑니다.</span></button></div>`;
    const grid=document.getElementById('battle-action-grid'); if(grid) grid.innerHTML=html;
  }
  function patchBattleEnd(){ /* fix15 disabled old end wrapper */ return;  const be=PB.battleEngine, c=core(); if(be && !be.__contentHotfixStart){be.__contentHotfixStart=true; const old=be.startBattle; be.startBattle=function(opts={}){const orig=opts.onComplete; return old.call(this,{...opts,onComplete:(payload)=>{FIX.endLocked=true; FIX.endPayload=payload||{}; let r; try{r=orig?orig(payload):undefined;}catch(e){console.warn(e);} setTimeout(()=>renderEndStats(payload),30); setTimeout(()=>renderEndStats(payload),350); return true;}});};}
    if(c && !c.__contentHotfixReturn){c.__contentHotfixReturn=true; const oldRet=c.returnToLobby; c.returnToLobby=function(){ if(FIX.endLocked){setTimeout(()=>renderEndStats(),20); return false;} return oldRet.apply(this,arguments);}; const oldCat=c.setCategory; c.setCategory=function(cat){ if(FIX.endLocked){setTimeout(()=>renderEndStats(),20); return false;} return oldCat.apply(this,arguments);};}
  }
  function patchPvpAutoSwitch(){ const be=PB.battleEngine; if(!be||be.__contentHotfixPvp) return; be.__contentHotfixPvp=true; const old=be.resolvePvpSyncedTurn; if(typeof old==='function'){ be.resolvePvpSyncedTurn=async function(a,b){ let sync; try{sync=await old.call(this,a,b);}catch(e){console.warn('PVP 턴 계산 복구',e); sync=be.exportPvpSyncState?.()||{}; sync.log=(sync.log||[]).concat('턴 계산을 복구했습니다.');} return autoSwitchFainted(sync); }; }}
  function firstAlive(team, skip){return (team||[]).findIndex((p,i)=>i!==skip && Number(p?.currentHp||0)>0);} function anyAlive(team){return (team||[]).some(p=>Number(p?.currentHp||0)>0);}
  function autoSwitchFainted(sync){ if(!sync) return sync; sync.log=sync.log||[]; if(sync.playerTeam && Number(sync.playerTeam[sync.allyIndex]?.currentHp||0)<=0){const n=firstAlive(sync.playerTeam,sync.allyIndex); if(n>=0){sync.allyIndex=n; sync.log.push(`${sync.playerTeam[n].name||sync.playerTeam[n].currentName||'포켓몬'}가 출전한다.`);}} if(sync.opponentTeam && Number(sync.opponentTeam[sync.enemyIndex]?.currentHp||0)<=0){const n=firstAlive(sync.opponentTeam,sync.enemyIndex); if(n>=0){sync.enemyIndex=n; sync.log.push(`${sync.opponentTeam[n].name||sync.opponentTeam[n].currentName||'포켓몬'}가 출전한다.`);}} sync.completed=!(anyAlive(sync.playerTeam)&&anyAlive(sync.opponentTeam)); return sync; }

  function patchDungeonLevels(){ const be=PB.battleEngine; if(!be||be.__contentHotfixDungeon) return; be.__contentHotfixDungeon=true; const old=be.startBattle; be.startBattle=function(opts={}){ try{ if(opts.mode==='dungeon' && Array.isArray(opts.opponentTeam)){ const maxLv=Math.max(5,...(player()?.squad||[]).map(p=>Number(p.level||5))); const lv=Math.max(1, Math.min(100, maxLv-(3+Math.floor(Math.random()*2)))); opts={...opts, opponentTeam:opts.opponentTeam.map(mon=>{ if(mon){mon.level=lv; core()?.recalculateRuntimeStats?.(mon,{fullHeal:true}); mon.currentHp=mon.maxHp;} return mon; })}; }}catch(e){console.warn(e);} return old.call(this,opts);}; }

  function safeOpenShop(page=0){ const c=core(), p=player(); const root=document.getElementById('modal-root'); if(!c||!root) return; const items=(c.getShopCatalog?.()||[]).filter(Boolean); const size=8, pages=Math.max(1,Math.ceil(items.length/size)); page=(Number(page||0)+pages)%pages; const rows=items.slice(page*size,page*size+size).map(it=>`<div class="safe-shop-card"><div class="safe-shop-row"><div><h3 class="shop-name">${esc((it.nameKo||'').replace(/^기술머신[:：]\s*/,''))}</h3><p class="shop-item-meta">${esc(it.category||'')}</p><p>${esc(it.description||it.battleEffect||'')}</p></div><span class="safe-shop-price">$${Number(it.price||0)}</span></div><div class="safe-shop-actions">${norm(it.id).startsWith('tm_')?`<button data-hotfix-shop-info="${esc(it.id)}">설명</button>`:''}<button class="buy" data-hotfix-shop-buy="${esc(it.id)}">구매</button></div></div>`).join(''); root.innerHTML=`<div class="overlay"><div class="modal large-modal safe-shop-modal"><div class="modal-header"><div class="modal-title-wrap"><h2>프렌들리숍</h2><p>보유 재화: $${Number(p?.money||0)}</p></div><button type="button" class="ghost-btn" data-hotfix-close-modal="1">닫기</button></div><div class="modal-body"><div class="shop-pager-row"><button class="chip-btn" data-hotfix-shop-page="${page-1}">◀</button><span class="shop-page-indicator">${page+1} / ${pages}</span><button class="chip-btn" data-hotfix-shop-page="${page+1}">▶</button></div><div class="safe-shop-grid">${rows||'<div class="empty-state">표시할 아이템이 없습니다.</div>'}</div></div></div></div>`; }
  function showItemInfo(id){ const it=core()?.state?.itemsById?.get?.(norm(id)) || (core()?.state?.itemList||[]).find(x=>norm(x.id)===norm(id)); if(!it) return; const root=document.getElementById('modal-root'); root.insertAdjacentHTML('beforeend',`<div class="overlay"><div class="modal-card p2-modal tm-detail-modal" style="background:#05070d;color:#fff;"><div class="modal-header"><h2>${esc((it.nameKo||'기술머신').replace(/^기술머신[:：]\s*/,''))}</h2><button class="close-btn" data-hotfix-close-top="1">✕</button></div><div class="modal-body"><p>${esc(it.description||'설명이 없습니다.').replace(/위력\s*(\d+)/g,'<span style="color:#ffd84f;font-weight:1000;">위력 $1</span>')}</p><p>${esc(it.battleEffect||'')}</p></div></div></div>`); }

  function renderRest(){ const shell=document.querySelector('.p2-online-shell') || document.getElementById('content-area'); if(!shell)return; const tabs=document.querySelector('.p2-tabs')?.outerHTML || ''; const m=currentMain(); const src=m?.base?.image||m?.base?.sprite||''; shell.innerHTML=tabs+`<section class="rest-area-hotfix"><button class="rest-exit" data-hotfix-rest-exit="1">나가기</button><img src="grass.gif" class="rest-grass"><div class="rest-mon"></div></section>`; const slot=shell.querySelector('.rest-mon'); clearInterval(FIX.restTimer); const spawn=()=>{ if(!slot)return; const x=48+Math.random()*28, y=17+Math.random()*18; slot.innerHTML=src?`<img src="${esc(src)}" style="right:${100-x}%;bottom:${y}%">`:`<span style="right:${100-x}%;bottom:${y}%">${esc(String(pName(m)).slice(0,1))}</span>`; setTimeout(()=>{ if(slot)slot.innerHTML=''; },2100);}; spawn(); FIX.restTimer=setInterval(spawn,3000); markActiveRest(); }
  function markActiveRest(){ document.querySelectorAll('[data-p2-tab]').forEach(b=>b.classList.toggle('active',b.dataset.p2Tab==='rest' && PB.phase2Online?.tab==='rest')); }
  function ensureRestTab(){ const tabs=document.querySelector('.p2-tabs'); if(!tabs || tabs.querySelector('[data-p2-tab="rest"]')) return; const rank=tabs.querySelector('[data-p2-tab="rankings"]'); const btn=document.createElement('button'); btn.dataset.p2Tab='rest'; btn.textContent='쉼터'; if(rank) tabs.insertBefore(btn,rank); else tabs.appendChild(btn); }

  function renderTierRankings(){ const shell=document.querySelector('.p2-online-shell'); if(!shell || PB.phase2Online?.tab!=='rankings') return; const tabs=shell.querySelector('.p2-tabs')?.outerHTML||''; const ranks=PB.phase2Online?.rankings||{ko:{},damage:{},tank:{}}; const tier=FIX.rankingTier||'monster'; const labels={monster:'몬스터볼',super:'수퍼볼',hyper:'하이퍼볼',master:'마스터볼'}; const make=(kind,title,label)=>{ const list=Object.values(ranks[kind]||{}).filter(r=>Number(r.score||0)>0 && (r.tier===tier || (tier==='monster' && r.tier==='beginner'))).sort((a,b)=>Number(b.score||0)-Number(a.score||0)).slice(0,10); return `<div class="p2-card"><h3>${title}</h3>${list.map((r,i)=>`<div class="p2-rank-row"><b>${i+1}</b><span>${esc(r.pokemonName||'포켓몬')}</span><small>${esc(r.nickname||'')} ${esc(r.characterName||'')}</small><em>${Number(r.score||0)} ${label}</em></div>`).join('')||'<p>아직 기록 없음</p>'}</div>`; }; shell.innerHTML=tabs+`<div class="p2-card"><h3>TOP10 랭킹</h3><p>경쟁전 배틀 기록 기준입니다.</p><div class="p2-rank-tier-tabs">${Object.entries(labels).map(([id,l])=>`<button data-hotfix-rank-tier="${id}" class="${tier===id?'active':''}">${l} 랭킹</button>`).join('')}</div></div><div class="p2-card"><h3>${labels[tier]} 랭킹</h3><div class="p2-rank-grid">${make('ko','KO 랭킹','KO')}${make('damage','데미지 랭킹','누적 피해')}${make('tank','탱커 랭킹','버틴피해')}</div></div>`; ensureRestTab(); }

  function decorate(){ ensureRestTab(); if(PB.phase2Online?.tab==='rest') renderRest(); else if(PB.phase2Online?.tab==='rankings' && !document.querySelector('.p2-rank-tier-tabs')) renderTierRankings(); document.querySelectorAll('.bloodline-text-v3,.battle-bloodline-v3,.p2-blood,.rt-blood,.blood-block,.v7-blood-block,.p2fp-blood-fixed,[class*="bloodline"]').forEach(bloodStyle); document.querySelectorAll('.stat-value.is-best').forEach(el=>{el.style.setProperty('color','#ff922e','important'); el.style.setProperty('-webkit-text-fill-color','#ff922e','important'); el.style.setProperty('border','0','important'); el.style.setProperty('box-shadow','none','important');}); if(FIX.endLocked && !document.querySelector('.hotfix-endstats,.v2-endstats,.p2fp-endstats')) renderEndStats(); const wait=document.querySelector('.pvp-ready-wait.big,.pvp-ready-wait'); if(wait && PB.phase2FinalStability?.roomId && !wait.querySelector('[data-hotfix-pvp-exit]')) wait.insertAdjacentHTML('beforeend',`<br><button class="p2-btn alt hotfix-exit" data-hotfix-pvp-exit="${esc(PB.phase2FinalStability.roomId)}">나가기</button>`); }

  function bind(){ window.addEventListener('click',async e=>{ const nav=e.target.closest?.('[data-nav]'); if(nav){ e.preventDefault(); e.stopImmediatePropagation(); FIX.endLocked=false; core()?.setCategory?.(nav.dataset.nav); return; } const shop=e.target.closest?.('#open-friendly-shop-btn'); if(shop){ e.preventDefault(); e.stopImmediatePropagation(); safeOpenShop(0); return; } const sp=e.target.closest?.('[data-hotfix-shop-page]'); if(sp){ e.preventDefault(); e.stopImmediatePropagation(); safeOpenShop(Number(sp.dataset.hotfixShopPage||0)); return; } const buy=e.target.closest?.('[data-hotfix-shop-buy]'); if(buy){ e.preventDefault(); e.stopImmediatePropagation(); const res=core()?.buyShopItem?.(core()?.state?.activePlayerId||'p1',buy.dataset.hotfixShopBuy); toast(res?.ok?`${res.item?.nameKo||'아이템'} 구매 완료`:(res?.message||'구매 실패')); safeOpenShop(Number(document.querySelector('.shop-page-indicator')?.textContent?.split('/')[0]||1)-1); return; } const info=e.target.closest?.('[data-hotfix-shop-info]'); if(info){ e.preventDefault(); e.stopImmediatePropagation(); showItemInfo(info.dataset.hotfixShopInfo); return; } if(e.target.closest?.('[data-hotfix-close-modal]')){ e.preventDefault(); e.stopImmediatePropagation(); document.getElementById('modal-root').innerHTML=''; return; } if(e.target.closest?.('[data-hotfix-close-top]')){ e.preventDefault(); e.stopImmediatePropagation(); e.target.closest('.overlay')?.remove(); return; } const rest=e.target.closest?.('[data-p2-tab="rest"]'); if(rest){ e.preventDefault(); e.stopImmediatePropagation(); if(PB.phase2Online) PB.phase2Online.tab='rest'; renderRest(); return; } const rank=e.target.closest?.('[data-hotfix-rank-tier]'); if(rank){ e.preventDefault(); e.stopImmediatePropagation(); FIX.rankingTier=rank.dataset.hotfixRankTier; renderTierRankings(); return; } if(e.target.closest?.('[data-hotfix-rest-exit]')){ e.preventDefault(); e.stopImmediatePropagation(); clearInterval(FIX.restTimer); if(PB.phase2Online) PB.phase2Online.tab='ranked'; ui()?.renderAll?.(); return; } if(e.target.closest?.('[data-hotfix-exit-lobby],[data-content-v2-exit],[data-final-exit-lobby],[data-battle-exit-lobby]')){ e.preventDefault(); e.stopImmediatePropagation(); FIX.endLocked=false; FIX.endPayload=null; if(PB.phase2ContentV2){PB.phase2ContentV2.endLocked=false; PB.phase2ContentV2.allowExit=true;} if(PB.phase2FinalStability){PB.phase2FinalStability.endShowing=false; PB.phase2FinalStability.allowLobbyUntil=Date.now()+3000;} core().state.currentScreen='lobby'; ui()?.renderAll?.(); return; } const pvpExit=e.target.closest?.('[data-hotfix-pvp-exit]'); if(pvpExit){ e.preventDefault(); e.stopImmediatePropagation(); try{await (online().db||null)?.ref(`battleRooms/${pvpExit.dataset.hotfixPvpExit}`).update({status:'cancelled',cancelledBy:(online().uid||''),updatedAt:Date.now()});}catch(err){} if(window.PB_REALTIME_PVP?.close) window.PB_REALTIME_PVP.close(); core().state.currentScreen='lobby'; ui()?.renderAll?.(); return; } }, true); }

  function patchRender(){ if(ui()&&!ui().__contentHotfixRender){ui().__contentHotfixRender=true; const old=ui().renderAll; ui().renderAll=function(){ const r=old.apply(this,arguments); setTimeout(decorate,0); return r;};} }
  function init(){ if(!core()||!ui()||!PB.battleEngine){setTimeout(init,120);return;} installCss(); patchBattleEnd(); patchPvpAutoSwitch(); patchDungeonLevels(); patchRender(); bind(); /* v8: recurring decorate disabled */ /* v8: disabled old content hotfix interval */ setTimeout(decorate,500); }
  document.addEventListener('DOMContentLoaded',()=>setTimeout(init,1400));
})();
