(function(){
  'use strict';
  const PB = window.POKEBATTLE || (window.POKEBATTLE = {});
  const F = PB.phase2FinalFix10 = PB.phase2FinalFix10 || { endLocked:false, payload:null, installed:false };
  const esc = (v)=>String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const norm = (v)=>String(v||'').toLowerCase().replace(/[^a-z0-9_가-힣]/g,'');
  const core=()=>PB.core; const ui=()=>PB.ui;
  function patchPrices(){ const c=core(); if(!c || c.__fix10PricePatch) return; c.__fix10PricePatch=true; const pricePatch=(it)=>{ const id=norm(it?.id); const x={...it}; if(id==='rare_candy') x.price=200; if(id==='mystery_egg') x.price=700; if(id==='good_potion') x.price=100; if(id==='revive_shard') x.price=200; return x; }; const oldCat=c.getShopCatalog; if(typeof oldCat==='function') c.getShopCatalog=function(){ return (oldCat.apply(this,arguments)||[]).filter(it=>!['mythic_fragment','artisan_knowledge'].includes(norm(it.id))).map(pricePatch); }; const oldInv=c.getFriendlyShopInventory; if(typeof oldInv==='function') c.getFriendlyShopInventory=function(){ return (oldInv.apply(this,arguments)||[]).filter(it=>!['mythic_fragment','artisan_knowledge'].includes(norm(it.id))).map(pricePatch); }; }
  function statRows(stats){ const s=stats||{}; const vals=Object.values(s); return (vals.length?vals:[]).map(x=>`<tr><td>${esc(x.name||x.pokemonName||'포켓몬')}</td><td>${Number(x.damageDealt||0)}</td><td>${Number(x.survivedDamage??x.damageTaken??0)}</td></tr>`).join('') || '<tr><td colspan="3">통계 없음</td></tr>'; }
  function renderEnd(payload){ F.endLocked=true; F.payload=payload||F.payload||{}; const c=core(); if(c?.state) c.state.currentScreen='battle'; const grid=document.getElementById('battle-action-grid'); if(!grid) return; const stats = F.payload?.stats || PB.battleEngine?.getSnapshot?.()?.stats || {}; grid.innerHTML=`<div class="fix10-endstats"><h3>배틀 통계</h3><table><thead><tr><th>포켓몬</th><th>딜량</th><th>버틴피해</th></tr></thead><tbody>${statRows(stats)}</tbody></table><button type="button" class="action-button fix10-exit-lobby" data-fix10-exit-lobby="1"><span class="action-title">나가기</span><span class="action-sub">로비로 돌아갑니다.</span></button></div>`; const log=document.getElementById('battle-log'); if(log) log.textContent='배틀이 종료되었습니다. 통계를 확인한 뒤 나가기를 눌러주세요.'; }
  function resetOldLocks(){ try{ if(PB.phase2ContentHotfix){PB.phase2ContentHotfix.endLocked=false;PB.phase2ContentHotfix.endPayload=null;} if(PB.phase2ContentV2){PB.phase2ContentV2.endLocked=false;PB.phase2ContentV2.allowExit=true;} if(PB.phase2FinalStability){PB.phase2FinalStability.endShowing=false;PB.phase2FinalStability.allowLobbyUntil=Date.now()+10000;} window.__FIX9_END_LOCK=false; window.__FIX9_LAST_END_STATS=null; }catch(e){} }
  function exitLobby(){ F.endLocked=false; F.payload=null; resetOldLocks(); const c=core(); if(c?.state){ c.state.currentScreen='lobby'; c.state.currentCategory=c.state.currentCategory||'squad'; } ui()?.closeModal?.(); ui()?.renderAll?.(); try{ ui()?.syncBgmForScreen?.(); ui()?.syncBgmVolume?.(); }catch(e){} }
  function patchBattleEnd(){ /* fix15 disabled old end wrapper */ return;  const u=ui(); if(u && !u.__fix10EndPatch){ u.__fix10EndPatch=true; u.showBattleEndStats=function(payload){ renderEnd(payload); }; }
    const c=core(); if(c && !c.__fix10ReturnPatch){ c.__fix10ReturnPatch=true; const oldRet=c.returnToLobby; c.returnToLobby=function(){ if(F.endLocked){ setTimeout(()=>renderEnd(),0); return false; } return oldRet.apply(this,arguments); }; const oldCat=c.setCategory; c.setCategory=function(cat){ if(F.endLocked){ setTimeout(()=>renderEnd(),0); return false; } return oldCat.apply(this,arguments); }; }
    const be=PB.battleEngine; if(be && !be.__fix10StartPatch){ be.__fix10StartPatch=true; const old=be.startBattle; be.startBattle=function(opts={}){ const original=opts.onComplete; return old.call(this,{...opts,onComplete:(payload)=>{ let handled=false; try{ handled= original ? original(payload) : false; }catch(e){ console.warn('onComplete failed',e); } renderEnd(payload); return true; }}); }; }
  }
  function colorMatchups(){
    document.querySelectorAll('.battle-matchup').forEach(n=>{ const t=n.textContent||''; n.classList.toggle('strong',t.includes('강함')); n.classList.toggle('weak',t.includes('약함')||t.includes('불리')); n.classList.toggle('neutral',!(t.includes('강함')||t.includes('약함')||t.includes('불리'))); });
    const snap=PB.battleEngine?.getSnapshot?.(); if(!snap || snap.menu!=='moves') return;
    const enemy = snap.turnSide==='ally' ? snap.enemy : snap.ally; const moves=snap.currentActor?.moves||[];
    document.querySelectorAll('.battle-move-button[data-battle-move]').forEach(btn=>{ const idx=Number(btn.dataset.battleMove); const mv=moves[idx]; if(!mv || !enemy || btn.querySelector('.battle-matchup')) return; let eff=1; try{ eff=PB.battleEngine?.getTypeEffectivenessValue?.(mv.type, enemy) ?? 1; }catch(e){} const label=eff>1?'강함':eff<1?'약함':'보통'; const cls=eff>1?'strong':eff<1?'weak':'neutral'; btn.insertAdjacentHTML('beforeend',`<span class="battle-matchup ${cls}">${esc(enemy.name||'상대')}에게 ${label}</span>`); });
  }
  function patchRankingBeginner(){
    document.querySelectorAll('.p2-rank-tier-tabs button,[data-hotfix-rank-tier]').forEach(btn=>{ if((btn.textContent||'').includes('몬스터볼') && !(btn.textContent||'').includes('비기너')) btn.title='비기너 기록도 포함됩니다.'; });
  }
  function installCss(){ if(document.getElementById('fix10-final-css')) return; const st=document.createElement('style'); st.id='fix10-final-css'; st.textContent=`
    #lobby-screen,.lobby-screen{background-image:linear-gradient(180deg,rgba(1,8,13,.06),rgba(1,8,13,.16)),url('pokebackground.png')!important;background-size:100% 100%!important;background-position:center center!important;background-repeat:no-repeat!important;background-color:#06111d!important;}
    .shop-modal,.safe-shop-modal,.fix10-shop-modal{background:linear-gradient(180deg,rgba(0,0,0,.18),rgba(0,0,0,.30)),url('shop.png') center center/contain no-repeat!important;background-color:#07111f!important;color:#fff!important;}
    .shop-modal .modal-header,.shop-modal .modal-body,.shop-modal .shop-item-card,.safe-shop-modal .modal-header,.safe-shop-modal .modal-body,.safe-shop-card{background:rgba(5,13,25,.38)!important;border-color:rgba(126,207,255,.23)!important;backdrop-filter:blur(7px)!important;color:#fff!important}.shop-tip-card{display:none!important;}
    .fix10-endstats{width:100%;background:#f7fbff!important;color:#050505!important;-webkit-text-fill-color:#050505!important;border:2px solid #111!important;border-radius:18px!important;padding:14px!important;box-shadow:0 10px 30px rgba(0,0,0,.22)!important}.fix10-endstats *{color:#050505!important;-webkit-text-fill-color:#050505!important;text-shadow:none!important}.fix10-endstats table{width:100%;border-collapse:collapse;background:#fff!important}.fix10-endstats th,.fix10-endstats td{border:1px solid rgba(0,0,0,.25);padding:6px;text-align:center}.fix10-endstats .action-button{margin-top:10px;background:#111!important;color:#fff!important;-webkit-text-fill-color:#fff!important}.fix10-endstats .action-button *{color:#fff!important;-webkit-text-fill-color:#fff!important}
    .battle-matchup{font-weight:1000!important;display:inline-block!important;margin-left:6px!important}.battle-matchup.strong{color:#159447!important;-webkit-text-fill-color:#159447!important}.battle-matchup.neutral{color:#050b18!important;-webkit-text-fill-color:#050b18!important}.battle-matchup.weak{color:#e58989!important;-webkit-text-fill-color:#e58989!important}
  `; document.head.appendChild(st); }
  document.addEventListener('click',function(e){ if(e.target.closest?.('[data-fix10-exit-lobby],.fix10-exit-lobby')){ e.preventDefault(); e.stopImmediatePropagation(); exitLobby(); return; } }, true);
  function decorate(){ patchPrices(); patchBattleEnd(); colorMatchups(); patchRankingBeginner(); if(F.endLocked) renderEnd(); }
  function init(){ installCss(); patchPrices(); patchBattleEnd(); decorate(); }
  init(); setInterval(decorate,500);
})();
