(function(){
  'use strict';
  const PB = window.POKEBATTLE || (window.POKEBATTLE = {});
  const F17 = PB.fix17Content = PB.fix17Content || { compareIds:[], mvp:{ week:{}, month:{} }, marketPage:0 };
  const TYPE_COLORS = { 노말:'#a8a878', 불꽃:'#f08030', 물:'#6890f0', 전기:'#f8d030', 풀:'#78c850', 얼음:'#98d8d8', 격투:'#c03028', 독:'#a040a0', 땅:'#e0c068', 비행:'#a890f0', 에스퍼:'#f85888', 벌레:'#a8b820', 바위:'#b8a038', 고스트:'#705898', 드래곤:'#7038f8', 악:'#705848', 강철:'#b8b8d0' };
  const STATS = [ ['hp','HP'], ['attack','공격'], ['defense','방어'], ['spAttack','특공'], ['spDefense','특방'], ['speed','스피드'] ];
  const TIERS = ['beginner','monster','super','hyper','master'];
  function c(){ return PB.core; }
  function ui(){ return PB.ui; }
  function online(){ return (window.PB_ONLINE_V3?.getOnlineState?.() || PB.online || {}); }
  function player(){ return c()?.getPlayer?.('p1') || c()?.getActivePlayer?.(); }
  function ch(){ return online().selectedCharacter || null; }
  function db(){ return online().db || null; }
  function key(){ const o=online(); return o.uid ? `${o.uid}_${o.selectedSlot || 'char1'}` : ''; }
  function esc(v){ return String(v ?? '').replace(/[&<>'"]/g, m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m])); }
  function norm(v){ return String(v || '').trim().toLowerCase(); }
  function toast(msg){ ui()?.showToast?.(msg); }
  function baseName(base){ return base?.nameKo || base?.name || '포켓몬'; }
  function monName(mon){ return mon?.currentName || mon?.name || baseName(mon?.base); }
  function statTotal(baseOrMon){ const s = baseOrMon?.speciesStats || baseOrMon?.stats || baseOrMon?.base?.speciesStats || baseOrMon?.base?.stats || {}; return STATS.reduce((a,[k])=>a+Number(s[k]||0),0); }
  function priceOf(base){ if(!base) return 0; if(window.PB_MARKET_PRICES && base.nameKo && window.PB_MARKET_PRICES[base.nameKo]) return Number(window.PB_MARKET_PRICES[base.nameKo]); const total=statTotal(base); const legend=c()?.shouldExcludeLegend?.(base)?2.8:1; return Math.max(400, Math.round((900 + total*8.2)*legend/100)*100); }
  function marketBuyPrice(base){ return Math.max(1, Math.ceil(priceOf(base)*1.5)); }
  function teamValue(pubOrPlayer){ const squad=(pubOrPlayer?.squad||[]).slice(0,3); return squad.reduce((sum,m)=>{ const base=m.base || c()?.state?.pokemonById?.get?.(Number(m.baseId||m.id)); return sum + priceOf(base); },0); }
  function currentWeekKey(){ const d=new Date(); const oneJan=new Date(d.getFullYear(),0,1); const week=Math.ceil((((d-oneJan)/86400000)+oneJan.getDay()+1)/7); return `${d.getFullYear()}-W${String(week).padStart(2,'0')}`; }
  function currentMonthKey(){ const d=new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`; }
  function highestSquadLevel(){ const p=player(); return Math.max(5,...(p?.squad||[]).map(x=>Number(x.level||5))); }
  function findBase(name){ const all=c()?.state?.allPokemon||[]; return all.find(p=>p?.nameKo===name || p?.nameEn===name) || null; }
  function fallbackBase(type){ const all=(c()?.state?.allPokemon||[]).filter(p=>p && !p.isMegaEvolution && (!type || (p.type||[]).includes(type))); return all[Math.floor(Math.random()*all.length)] || (c()?.state?.allPokemon||[])[0] || null; }
  const F17_MEDIA = {
    '원시그란돈':{type:'video',src:'media-videos/PrimalGroudon.mp4',poster:'skin-sprites/grd.png'},
    '원시가이오가':{type:'video',src:'media-videos/PrimalKyogre.mp4',poster:'skin-sprites/gga.png'},
    '염버니':{type:'video',src:'media-videos/Scorbunny.mp4'},
    '래비풋':{type:'video',src:'media-videos/Raboot.mp4'},
    '에이스번':{type:'video',src:'media-videos/Cinderace.mp4'},
    '울머기':{type:'video',src:'media-videos/Sobble.mp4'},
    '누겔레온':{type:'video',src:'media-videos/Drizzile.mp4'},
    '인텔리레온':{type:'video',src:'media-videos/Inteleon.mp4'},
    '인텔라레온':{type:'video',src:'media-videos/Inteleon.mp4'},
    '흥나숭':{type:'video',src:'media-videos/Grookey.mp4'},
    '채키몽':{type:'video',src:'media-videos/Thwackey.mp4'},
    '고릴타':{type:'video',src:'media-videos/Rillaboom.mp4'},
    '그란돈':{type:'video',src:'media-videos/Groudon.mp4',poster:'skin-sprites/grd.png'},
    '가이오가':{type:'video',src:'media-videos/Kyogre.mp4',poster:'skin-sprites/gga.png'},
    '아르세우스':{type:'video',src:'media-videos/Arceus.mp4',poster:'skin-sprites/arc.png'},
    '디아루가':{type:'video',src:'media-videos/Dialga.mp4',poster:'skin-sprites/drg.png'},
    '펄기아':{type:'video',src:'media-videos/Palkia.mp4',poster:'skin-sprites/pga.png'},
    '기라티나':{type:'video',src:'media-videos/Giratina.mp4',poster:'skin-sprites/grt.png'},
    '다크라이':{type:'video',src:'media-videos/darkrai.mp4',poster:'skin-sprites/dk.png'},
    '레쿠쟈':{type:'video',src:'media-videos/Rayquaza.mp4',poster:'skin-sprites/rkj.png'},
    '뮤츠':{type:'video',src:'media-videos/Mewtwo.mp4',poster:'skin-sprites/mtz.png'},
    '루기아':{type:'video',src:'media-videos/Lugia.mp4',poster:'skin-sprites/rga.png'},
    '칠색조':{type:'video',src:'media-videos/Ho-Oh.mp4',poster:'skin-sprites/csj.png'},
    '레시라무':{type:'video',src:'media-videos/Reshiram.mp4',poster:'skin-sprites/rsrm.png'},
    '제크로무':{type:'video',src:'media-videos/Zekrom.mp4',poster:'skin-sprites/jcr.png'},
    '게노세크트':{type:'video',src:'media-videos/Genesect.mp4',poster:'skin-sprites/gnc.png'},
    '쉐이미':{type:'video',src:'media-videos/Shaymin.mp4',poster:'skin-sprites/shm.png'}
  };
  function avatar(base, size=46){
    if(!base) return `<span class="f17-avatar" style="width:${size}px;height:${size}px;">?</span>`;
    const fallback = F17_MEDIA[base.nameKo] || F17_MEDIA[base.mediaNameKo] || null;
    const src = String((fallback && fallback.src) || base.image || base.sprite || base.asset || base.spriteUrl || base.media || '');
    const poster = String((fallback && fallback.poster) || base.poster || '');
    const color=TYPE_COLORS[(base.type||[])[0]] || '#7ecfff';
    const letter=esc(String(base.nameKo||'?').slice(0,1));
    if(src && /\.mp4($|\?)/i.test(src)) return `<span class="f17-avatar" style="width:${size}px;height:${size}px;background:${color};"><video src="${esc(src)}" ${poster?`poster="${esc(poster)}"`:''} muted autoplay loop playsinline preload="metadata" onerror="this.style.display='none';this.parentNode.textContent='${letter}'"></video></span>`;
    if(src) return `<span class="f17-avatar" style="width:${size}px;height:${size}px;background:${color};"><img src="${esc(src)}" alt="${esc(base.nameKo)}" onerror="this.style.display='none';this.parentNode.textContent='${letter}'"></span>`;
    return `<span class="f17-avatar" style="width:${size}px;height:${size}px;background:${color};">${letter}</span>`;
  }
  function typeBadges(types){ return (types||[]).map(t=>`<span class="f17-type" style="background:${TYPE_COLORS[t]||'#789'}">${esc(t)}</span>`).join(''); }
  function statsAt(base, level){ try { return c()?.calculateStatsForLevel?.(base, level) || {}; } catch(e){ return {}; } }
  function statsLine(base, level, compareStats){ const s=statsAt(base, level); const total=STATS.reduce((a,[k])=>a+Number(s[k]||0),0); const rows=STATS.map(([k,l])=>{ const hi=compareStats && Number(s[k]||0)>Number(compareStats[k]||0); return `<div class="f17-stat"><span>${l}</span><b class="${hi?'f17-blue':''}">${Number(s[k]||0)}</b></div>`; }).join(''); return `<div class="f17-statbox"><h4>Lv.${level} 총합 ${total}</h4>${rows}</div>`; }
  function ensureState(){
    const cc=ch(); if(!cc) return null;
    cc.titles = cc.titles || { earned:{}, equipped:null };
    cc.achievements = cc.achievements || { claimed:{} };
    cc.records = cc.records || { currentWinStreak:0, maxWinStreak:0, competitiveWins:0, competitiveLosses:0 };
    cc.ownedSpeciesHistory = Array.isArray(cc.ownedSpeciesHistory) ? cc.ownedSpeciesHistory : [];
    cc.mvp = cc.mvp || { weekKey:currentWeekKey(), monthKey:currentMonthKey(), weekWins:0, monthWins:0, awardedWeek:{}, awardedMonth:{}, challenges:{} };
    if(cc.mvp.weekKey !== currentWeekKey()){ cc.mvp.weekKey=currentWeekKey(); cc.mvp.weekWins=0; }
    if(cc.mvp.monthKey !== currentMonthKey()){ cc.mvp.monthKey=currentMonthKey(); cc.mvp.monthWins=0; }
    return cc;
  }
  function updateOwnedHistory(){ const cc=ensureState(); const p=player(); if(!cc||!p) return; const set=new Set(cc.ownedSpeciesHistory||[]); [...(p.squad||[]),...(p.reserve||[])].forEach(m=>{ const id=Number(m?.base?.id || m?.id || 0); if(id) set.add(id); }); cc.ownedSpeciesHistory=[...set]; }
  function ownedBases(){ const ids=new Set((ensureState()?.ownedSpeciesHistory||[]).map(Number)); const cur=[...(player()?.squad||[]),...(player()?.reserve||[])]; cur.forEach(m=>{ const id=Number(m?.base?.id||m?.id||0); if(id) ids.add(id); }); return (c()?.state?.allPokemon||[]).filter(b=>ids.has(Number(b.id))); }
  const ACHIEVEMENTS = [
    {id:'water_master', title:'바다전문가', desc:'물 타입 포켓몬 6종 이상 획득', progress:()=>ownedBases().filter(b=>(b.type||[]).includes('물')).length, goal:6, reward:'알 1개 + 5000원'},
    {id:'myth_witness', title:'신화목격자', desc:'디아루가와 펄기아를 모두 획득', progress:()=>['디아루가','펄기아'].filter(n=>ownedBases().some(b=>b.nameKo===n)).length, goal:2, reward:'거대알 1개 + 5000원'},
    {id:'immortal', title:'불멸', desc:'경쟁전 5연승 달성', progress:()=>Number(ensureState()?.records?.maxWinStreak||0), goal:5, reward:'알 1개 + 5000원'},
    {id:'land_ruler', title:'대지의지배자', desc:'그란돈 또는 원시그란돈 획득', progress:()=>ownedBases().some(b=>['그란돈','원시그란돈'].includes(b.nameKo))?1:0, goal:1, reward:'거대알 1개 + 5000원'},
    {id:'sea_ruler', title:'바다의지배자', desc:'가이오가 또는 원시가이오가 획득', progress:()=>ownedBases().some(b=>['가이오가','원시가이오가'].includes(b.nameKo))?1:0, goal:1, reward:'거대알 1개 + 5000원'},
    {id:'arceus_ruler', title:'지배자', desc:'아르세우스 획득', progress:()=>ownedBases().some(b=>b.nameKo==='아르세우스')?1:0, goal:1, reward:'특별알 1개 + 5000원'},
    {id:'guardian', title:'수호자', desc:'칠색조 획득', progress:()=>ownedBases().some(b=>b.nameKo==='칠색조')?1:0, goal:1, reward:'알 1개 + 5000원'},
    {id:'hunter', title:'사냥꾼', desc:'수퍼볼 이상에서 KO 30 이상 포켓몬 보유', progress:()=>Math.max(0,...([...(player()?.squad||[]),...(player()?.reserve||[])].map(m=>Number(m.koCount||0)))), goal:30, reward:'거대알 1개 + 5000원'},
    {id:'collector', title:'컬렉터', desc:'포켓몬 20종 이상 획득', progress:()=>ownedBases().length, goal:20, reward:'알 2개 + 5000원'},
    {id:'rich_team', title:'황금스쿼드', desc:'팀가치 30000원 이상 달성', progress:()=>teamValue(player()), goal:30000, reward:'거대알 1개 + 7000원'},
    {id:'enhancer', title:'강화장인', desc:'+5 강화 포켓몬 보유', progress:()=>Math.max(0,...([...(player()?.squad||[]),...(player()?.reserve||[])].map(m=>Number(m.enhanceLevel||0)))), goal:5, reward:'강화보호권 1개 + 5000원'},
    {id:'legend_collector', title:'전설수집가', desc:'전설/환상 포켓몬 3종 이상 획득', progress:()=>ownedBases().filter(b=>c()?.shouldExcludeLegend?.(b)).length, goal:3, reward:'특별알 1개 + 8000원'}
  ];
  function awardAchievement(a){
    const cc=ensureState(); if(!cc || cc.achievements.claimed[a.id]) return false;
    if(a.progress() < a.goal) return false;
    cc.achievements.claimed[a.id]=Date.now(); cc.titles.earned[a.title]=true;
    const p=player(); if(p) c()?.addMoney?.('p1', a.id==='rich_team'||a.id==='legend_collector'?7000:5000);
    if(a.id==='myth_witness'||a.id==='land_ruler'||a.id==='sea_ruler'||a.id==='hunter'||a.id==='rich_team') c()?.addConsumable?.('p1','huge_egg',1);
    else if(a.id==='arceus_ruler'||a.id==='legend_collector') c()?.addConsumable?.('p1','special_egg',1);
    else if(a.id==='enhancer') c()?.addConsumable?.('p1','enhance_guard',1);
    else c()?.addConsumable?.('p1','mystery_egg',1);
    if(!cc.titles.equipped) cc.titles.equipped=a.title;
    toast(`칭호 획득: ${a.title}`);
    saveAndPublish(); return true;
  }
  function scanAchievements(){ updateOwnedHistory(); ACHIEVEMENTS.forEach(awardAchievement); }
  async function saveAndPublish(){ try{ await window.PB_ONLINE_V3?.saveCharacter?.(); }catch(e){} publishExtra(); }
  async function publishExtra(){ const cc=ensureState(); const d=db(), k=key(); if(!d||!k||!cc) return; const p=player(); const payload={ title:cc.titles.equipped||'', titles:Object.keys(cc.titles.earned||{}), records:cc.records||{}, teamValue:teamValue(p), mostExpensivePokemon:mostExpensiveName(p) }; const sig=JSON.stringify(payload); const now=Date.now(); if(F17.__lastPublicSig===sig && now-Number(F17.__lastPublicAt||0)<45000) return; F17.__lastPublicSig=sig; F17.__lastPublicAt=now; try{ await d.ref(`playerPublicList/${k}`).update({...payload, updatedAt:now}); }catch(e){} }
  function mostExpensiveName(p){ const list=[...(p?.squad||[]),...(p?.reserve||[])]; let best=null; list.forEach(m=>{ const price=priceOf(m.base); if(!best||price>best.price) best={name:monName(m), price}; }); return best ? `${best.name} ${best.price}원` : '없음'; }
  function renderTabRow(active){ const tabs=[['ranked','경쟁전'],['mow','주간 MVP(MoW)'],['mom','이달의 MVP(MoM)'],['players','플레이어 랭킹'],['champion','챔피언'],['friendly','친선배틀'],['challenge','챌린지'],['market','시스템마켓'],['playerMarket','플레이어 마켓'],['rankings','포켓몬 랭킹'],['achievements','도전과제 및 칭호']]; return `<div class="online-tab-row p2-tabs">${tabs.map(([id,label])=>`<button data-p2-tab="${id}" class="${active===id?'active':''}">${label}</button>`).join('')}</div>`; }
  function renderAchievements(){ scanAchievements(); const cc=ensureState(); const rows=ACHIEVEMENTS.map(a=>{ const v=a.progress(), done=v>=a.goal, claimed=cc?.achievements?.claimed?.[a.id]; return `<div class="f17-card"><div class="f17-title-row"><h3>${esc(a.title)}</h3><span class="mini-badge">${claimed?'칭호 획득':done?'보상 지급':'진행중'}</span></div><p>${esc(a.desc)}</p><div class="f17-progress"><i style="width:${Math.min(100,Math.round(v/a.goal*100))}%"></i></div><small>진행도 ${Math.min(v,a.goal)} / ${a.goal} · 보상 ${esc(a.reward)}</small></div>`; }).join(''); const titles=Object.keys(cc?.titles?.earned||{}); const titleRows=titles.map(t=>`<button class="chip-btn ${cc.titles.equipped===t?'active':''}" data-f17-equip-title="${esc(t)}">${cc.titles.equipped===t?'장착중 ':''}${esc(t)}</button>`).join('') || '<div class="empty-state">아직 획득한 칭호가 없습니다.</div>'; return `<section class="placeholder-stack p2-online-shell">${renderTabRow('achievements')}<div class="f17-card"><h3>도전과제 및 칭호</h3><p>조건을 달성하면 자동으로 칭호와 보상금, 알 보상을 받습니다. 장착한 칭호는 로비 닉네임 왼쪽과 플레이어 랭킹 정보에 표시됩니다.</p></div><div class="f17-card"><h3>칭호 목록</h3><div class="online-mini-row">${titleRows}</div></div>${rows}</section>`; }
  function renderMarket(){ const all=(c()?.state?.allPokemon||[]).filter(b=>b && !b.isMegaEvolution); const pageSize=8, pages=Math.max(1,Math.ceil(all.length/pageSize)); F17.marketPage=(Number(F17.marketPage||0)+pages)%pages; const slice=all.slice(F17.marketPage*pageSize,F17.marketPage*pageSize+pageSize); const rows=slice.map(base=>`<div class="online-market-row f17-market-row">${avatar(base,54)}<div><div class="online-market-name">${esc(base.nameKo)}</div><div class="online-market-meta">${esc((base.type||[]).join(' / '))} · Lv.5 · 종족값 총합 ${statTotal(base)}</div></div><div class="f17-market-actions"><span class="online-price">$${marketBuyPrice(base)}</span><button class="chip-btn" data-f17-market-info="${base.id}">정보확인</button><button class="chip-btn" data-f17-market-compare="${base.id}">비교</button><button class="chip-btn" data-f17-market-buy="${base.id}">구입</button></div></div>`).join(''); const p=player(); const reserve=(p?.reserve||[]).slice(0,8).map(m=>`<button class="online-small-btn alt" data-f17-market-sell="${esc(m.uid)}">${esc(monName(m))} ${m.marketFree?'$0':('$'+Math.floor(priceOf(m.base)/2))}</button>`).join('') || '<span class="section-caption">판매 가능한 리저브 포켓몬 없음</span>'; return `<section class="placeholder-stack p2-online-shell">${renderTabRow('market')}<div class="placeholder-card"><div class="item-title-row"><h3>시스템마켓</h3><span class="mini-badge">${F17.marketPage+1}/${pages}</span></div><p>총합스탯, 50/100레벨 정보, 기술 목록, 2마리 비교를 확인할 수 있습니다. 최초 스타팅 2마리와 최초 랜덤 보상 1마리는 판매 시 0원입니다.</p><div class="online-mini-row"><button class="chip-btn" data-f17-market-page="prev">◀</button><button class="chip-btn" data-f17-market-page="next">▶</button><button class="chip-btn" data-f17-clear-compare="1">비교초기화 (${F17.compareIds.length}/2)</button></div></div><div class="online-market-list">${rows}</div><div class="placeholder-card"><h3>내 포켓몬 판매</h3><div class="online-mini-row">${reserve}</div></div></section>`; }
  function renderPlayerMarket(){ const phase=PB.phase2Online||{}; const listings=Object.entries(phase.listings||{}).map(([id,l])=>({id,...l})).filter(l=>!l.sold&&!l.cancelled).sort((a,b)=>Number(b.createdAt||0)-Number(a.createdAt||0)); const rows=listings.map(l=>{ const mon=l.publicPokemon||l.pokemon||{}; const base=c()?.state?.pokemonById?.get?.(Number(mon.baseId)); const total=statTotal(base); const mine=l.sellerKey===key(); return `<div class="p2-player-row">${avatar(base,48)}<div class="p2-grow"><b>${esc(mon.name||'포켓몬')}</b><small>Lv.${Number(mon.level||5)} · 총합스탯 ${total} · 판매자 ${esc(l.sellerName||'')}</small><div>${typeBadges(mon.types||base?.type||[])} <span class="p2-blood p2-blood-gray">${esc(normalizeBloodline(mon.bloodline))}</span></div></div><div class="p2-col"><b>${Number(l.price||0)}원</b><button class="p2-btn alt" data-p2-listing-moves="${esc(l.id)}">기술 목록</button>${mine?`<button class="p2-btn alt" data-p2-cancel-listing="${esc(l.id)}">취소</button>`:`<button class="p2-btn" data-p2-buy-listing="${esc(l.id)}">구매</button>`}</div></div>`; }).join('') || '<div class="p2-card">판매 게시된 포켓몬이 없습니다.</div>'; const reserve=(player()?.reserve||[]).slice(0,12).map(m=>`<button class="p2-btn alt" data-p2-list-pokemon="${esc(m.uid)}">${esc(monName(m))} 총합 ${statTotal(m.base)}</button>`).join('') || '<span class="p2-muted">게시 가능한 리저브 포켓몬 없음</span>'; return `<section class="placeholder-stack p2-online-shell">${renderTabRow('playerMarket')}<div class="p2-card"><h3>플레이어 마켓</h3><p>판매 포켓몬의 총합스탯과 기술 목록을 확인할 수 있습니다.</p></div><div class="p2-list">${rows}</div><div class="p2-card"><h3>판매 게시</h3><div class="online-mini-row">${reserve}</div></div></section>`; }
  function normalizeBloodline(v){ const s=String(v||'normal'); if(s.includes('뮤')||s==='mew'||s==='mew_descendant') return '뮤의 후손'; if(s.includes('고대')||s==='ancient') return '고대혈통'; if(s.includes('우수')||['elite','superior','great'].includes(s)) return '우수혈통'; return '일반혈통'; }
  function renderPlayersRanking(){ const phase=PB.phase2Online||{}; const arr=Object.entries(phase.players||{}).map(([id,p])=>({id,...p})).filter(p=>p&&!p.deleted&&!p.hidden&&p.characterName).sort((a,b)=>(Number(b.rankValue||0)-Number(a.rankValue||0))||Number(b.updatedAt||0)-Number(a.updatedAt||0)); const rows=arr.map((p,i)=>{ const main=p.mainPokemon||(p.squad||[])[0]; const base=c()?.state?.pokemonById?.get?.(Number(main?.baseId)); const title=p.title?`<span class="f17-title-badge">${esc(p.title)}</span>`:''; return `<div class="p2-player-row ${p.key===key()?'p2-me-row':''}"><div class="p2-rank-no">${i+1}</div>${avatar(base,46)}<div class="p2-grow"><b>${title}${p.key===key()?'내 정보 · ':''}${esc(p.nickname||'')} ${esc(p.characterName||'트레이너')}</b><small>${esc(p.tierLabel||'')} · 경쟁전 ${Number(p.rankWins||0)}승 ${Number(p.rankLosses||0)}패 · 팀가치 ${Number(p.teamValue||teamValue(p)).toLocaleString()}원</small><div>${main?`${esc(main.name||'포켓몬')} Lv.${Number(main.level||5)} ${typeBadges(main.types||[])}`:'메인 포켓몬 없음'}</div></div><div class="p2-col"><button class="p2-btn" data-f17-view-squad="${esc(p.key||p.id)}">출전목록</button><button class="p2-btn alt" data-f17-view-info="${esc(p.key||p.id)}">정보</button></div></div>`; }).join('') || '<div class="p2-card">접속/저장된 플레이어가 없습니다.</div>'; return `<section class="placeholder-stack p2-online-shell">${renderTabRow('players')}<div class="p2-card"><h3>플레이어 랭킹</h3><p>경쟁전 티어, 팀가치, 장착 칭호와 기록을 기준으로 플레이어 정보를 확인합니다.</p></div><div class="p2-list">${rows}</div></section>`; }
  function renderMvp(kind){ const isWeek=kind==='week'; const data=F17.mvp[isWeek?'week':'month']||{}; const arr=Object.entries(data).map(([id,r])=>({id,...r})).sort((a,b)=>Number(b.wins||0)-Number(a.wins||0)).slice(0,10); const title=isWeek?'주간 MVP(MoW)':'이달의 MVP(MoM)'; const rows=arr.map((r,i)=>`<div class="p2-rank-row"><b>${i+1}</b><span>${esc(r.characterName||r.nickname||'트레이너')}</span><small>${esc(r.tierLabel||'')} · ${Number(r.wins||0)}승</small><em>${r.title?`[${esc(r.title)}] `:''}${Number(r.wins||0)}승</em></div>`).join('') || '<p>아직 집계된 승리 기록이 없습니다.</p>'; maybeAwardMvp(kind, arr[0]); return `<section class="placeholder-stack p2-online-shell">${renderTabRow(isWeek?'mow':'mom')}<div class="p2-card"><h3>${title}</h3><p>${isWeek?'한 주':'한 달'} 동안 경쟁전에서 가장 많이 승리한 플레이어가 MVP가 됩니다. 현재 1위가 되면 1회 5000원을 받습니다.</p></div><div class="p2-card">${rows}</div></section>`; }
  function maybeAwardMvp(kind, top){ const cc=ensureState(); if(!cc||!top||top.key!==key()||Number(top.wins||0)<=0) return; const k=kind==='week'?currentWeekKey():currentMonthKey(); const bucket=kind==='week'?'awardedWeek':'awardedMonth'; if(cc.mvp[bucket]?.[k]) return; cc.mvp[bucket]=cc.mvp[bucket]||{}; cc.mvp[bucket][k]=true; c()?.addMoney?.('p1',5000); toast(`${kind==='week'?'주간 MVP':'이달의 MVP'} 보상 +5000원`); saveAndPublish(); }
  function renderChallengeAppend(html){ const add=`<div class="p2-card f17-mvp-challenge"><h3>MoW / MoM 스쿼드 AI 도전</h3><p>현재 MVP 스쿼드의 AI 트레이너와 배틀합니다. 승리 전까지 재도전 가능하며, 하루 1회 승리 보상으로 거대알조각 2개를 얻습니다.</p><div class="online-mini-row"><button class="p2-btn" data-f17-mvp-challenge="week">주간 MVP 스쿼드 도전</button><button class="p2-btn" data-f17-mvp-challenge="month">이달의 MVP 스쿼드 도전</button></div></div>`; return String(html).replace('</section>', `${add}</section>`); }
  function showMarketInfo(baseId){ const base=c()?.state?.pokemonById?.get?.(Number(baseId)); if(!base) return; const moves=(base.moves||[]).map(m=>`<div class="f17-move"><b>${esc(m.nameKo||m.name||'기술')}</b><small>${esc(m.type||'노말')} · ${esc(m.category||'')} · 위력 ${esc(m.power||'-')} · 명중 ${esc(m.accuracy||'-')} · PP ${esc(m.pp||'-')}</small><p>${esc(m.description||'')}</p></div>`).join('') || '<p>기술 정보 없음</p>'; openModal(`${base.nameKo} 정보확인`, `<div class="f17-info-head">${avatar(base,72)}<div><h3>${esc(base.nameKo)}</h3><p>${typeBadges(base.type)} 종족값 총합 ${statTotal(base)} · 가격 ${marketBuyPrice(base)}원</p></div></div><div class="f17-compare-grid">${statsLine(base,50)}${statsLine(base,100)}</div><h3>스킬 목록</h3>${moves}`); }
  function showCompare(){ if(F17.compareIds.length<2){ toast('비교할 포켓몬을 2마리 선택하세요.'); return; } const [aId,bId]=F17.compareIds.slice(-2); const a=c()?.state?.pokemonById?.get?.(Number(aId)), b=c()?.state?.pokemonById?.get?.(Number(bId)); if(!a||!b) return; const a50=statsAt(a,50), b50=statsAt(b,50), a100=statsAt(a,100), b100=statsAt(b,100); openModal('포켓몬 비교', `<div class="f17-compare-head"><div>${avatar(a,64)}<b>${esc(a.nameKo)}</b></div><div>${avatar(b,64)}<b>${esc(b.nameKo)}</b></div></div><h3>50레벨 기준</h3><div class="f17-compare-grid">${statsLine(a,50,b50)}${statsLine(b,50,a50)}</div><h3>100레벨 기준</h3><div class="f17-compare-grid">${statsLine(a,100,b100)}${statsLine(b,100,a100)}</div>`); }
  function openModal(title, html){ const root=document.getElementById('modal-root'); if(!root) return; root.innerHTML=`<div class="overlay"><div class="modal-card p2-modal f17-modal"><div class="modal-header"><h2>${esc(title)}</h2><button class="close-btn" data-f17-close-modal="1">✕</button></div><div class="modal-body">${html}</div></div></div>`; }
  function buyMarket(baseId){ const base=c()?.state?.pokemonById?.get?.(Number(baseId)); const p=player(); if(!base||!p) return; const price=marketBuyPrice(base); if(!c()?.spendMoney?.('p1',price)){ toast('재화가 부족합니다.'); return; } const m=c().createRuntimePokemon(base,5); ensureBloodline(m); c().addPokemonToReserve?.('p1',m); saveAndPublish(); ui()?.renderAll?.(); toast(`${base.nameKo} 구입 완료`); }
  function sellMarket(uid){ const p=player(); const idx=(p?.reserve||[]).findIndex(m=>m.uid===uid); if(!p||idx<0) return; const [m]=p.reserve.splice(idx,1); const amount=m.marketFree?0:Math.floor(priceOf(m.base)/2); c()?.addMoney?.('p1',amount); saveAndPublish(); ui()?.renderAll?.(); toast(`${monName(m)} 판매 +$${amount}`); }
  function ensureBloodline(m){ if(!m || m.bloodline) return m; const r=Math.random(); m.bloodline = r<0.02?'mew':r<0.10?'ancient':r<0.35?'elite':'normal'; return m; }
  function renderPlayerSquadModal(k){ const p=(PB.phase2Online?.players||{})[k]; if(!p) return; const rows=(p.squad||[]).map(mon=>{ const base=c()?.state?.pokemonById?.get?.(Number(mon.baseId)); return `<div class="p2-player-row">${avatar(base,48)}<div class="p2-grow"><b>${esc(mon.name||'포켓몬')}</b><small>Lv.${Number(mon.level||5)} · 총합스탯 ${statTotal(base)} · ${esc((mon.types||[]).join('/'))}</small><div>${typeBadges(mon.types||[])} <span class="p2-blood p2-blood-gray">${esc(normalizeBloodline(mon.bloodline))}</span></div></div></div>`; }).join('') || '<p>출전 포켓몬 없음</p>'; openModal(`${p.characterName||'플레이어'} 출전목록`, rows); }
  function renderPlayerInfoModal(k){ const p=(PB.phase2Online?.players||{})[k]; if(!p) return; const titles=(p.titles||[]).join(', ') || (p.title||'없음'); const rec=p.records||{}; openModal(`${p.characterName||'플레이어'} 정보`, `<div class="f17-card"><h3>${p.title?`[${esc(p.title)}] `:''}${esc(p.characterName||'트레이너')}</h3><p>획득 칭호: ${esc(titles)}</p><p>최대 연승: ${Number(rec.maxWinStreak||0)} · 현재 연승: ${Number(rec.currentWinStreak||0)}</p><p>팀가치: ${Number(p.teamValue||teamValue(p)).toLocaleString()}원</p><p>가장 비싼 포켓몬: ${esc(p.mostExpensivePokemon||'없음')}</p><p>경쟁전 기록: ${Number(p.rankWins||0)}승 ${Number(p.rankLosses||0)}패</p></div>`); }
  function getPromotionTrainer(st){ const tier=st.tier||'beginner', rank=Number(st.rank||3); if(tier==='beginner') return {name:'이슬이', team:['라프라스','갸라도스','꼬부기'], bgm:'battle.mp3'}; const map={ monster:{3:['웅이',['램펄드','고지','괴력몬'],'battle.mp3'],2:['난천',['화강돌','한카리아스','밀로틱'],'cynthia.mp3'],1:['빛나',['엠페르트','토대부기','초염몽'],'battle.mp3']}, super:{3:['목호',['망나뇽','갸라도스','리자몽'],'hgsschampion.mp3'],2:['노간주',['볼카모스','버프론','액스라이즈'],'battle.mp3'],1:['태홍',['갸라도스','포푸니라','헬가'],'team_galactic.mp3']}, hyper:{3:['레드',['피카츄','리자몽','거북왕'],'battle.mp3'],2:['그린',['이상해꽃','갸라도스','윈디'],'hgssrival.mp3'],1:['N',['제크로무','아르세우스','조로아크'],'battle.mp3']}, master:{3:['지우',['피카츄','리자몽','루카리오'],'battle.mp3'],2:['이슬이',['라프라스','갸라도스','가이오가'],'battle.mp3'],1:['웅이',['램펄드','고지','괴력몬'],'battle.mp3']} }; const x=map[tier]?.[rank]||map.monster[3]; return {name:x[0], team:x[1], bgm:x[2]}; }
  function makeTeam(names){ const max=highestSquadLevel(); return names.slice(0,3).map((n,i)=>{ const base=findBase(n)||fallbackBase(i===0?'노말':null); const lv=Math.max(1, Math.min(100, max - (i===0?0:(i===1?1:2)))); const m=c().createRuntimePokemon(base, lv); ensureBloodline(m); return m; }); }
  function makeRandomTeam(){ const all=(c()?.state?.allPokemon||[]).filter(b=>b&&!b.isMegaEvolution); const max=highestSquadLevel(); return all.sort(()=>Math.random()-0.5).slice(0,3).map((b,i)=>c().createRuntimePokemon(b, Math.max(1, max-(i?2:0)))); }
  function cloneForBattle(m){ const x=c().createRuntimePokemon(m.base, Number(m.level||5)); x.sourceUid=m.uid; x.moves=(m.moves||[]).slice(0,4).map(a=>({...a})); x.heldItems=(m.heldItems||[]).map(a=>({...a})); x.heldItem=x.heldItems[0]||null; x.bloodline=m.bloodline; x.enhanceLevel=Number(m.enhanceLevel||0); c().recalculateRuntimeStats?.(x,{fullHeal:true}); return x; }
  function currentTier(){ const cc=ensureState(); cc.competitive=cc.competitive || {tier:'beginner',rank:3,points:0,promotionReady:false,wins:0,losses:0}; return cc.competitive; }
  function tierLabel(st){ const names={beginner:'비기너',monster:'몬스터볼',super:'수퍼볼',hyper:'하이퍼볼',master:'마스터볼'}; return st.tier==='beginner'?`${names[st.tier]} ${Number(st.points||0)}/50`:`${names[st.tier]} ${Number(st.rank||3)}티어 ${Number(st.points||0)}/100`; }
  function tierIndex(t){ return Math.max(0,TIERS.indexOf(t||'beginner')); }
  function advanceTier(st){ st.points=0; st.promotionReady=false; if(st.tier==='beginner'){ st.tier='monster'; st.rank=3; return; } if(Number(st.rank||3)>1) st.rank=Number(st.rank||3)-1; else { st.tier=TIERS[Math.min(TIERS.length-1,tierIndex(st.tier)+1)]; st.rank=3; } }
  function updateTier(won, promo){ const st=currentTier(); if(won) st.wins=Number(st.wins||0)+1; else st.losses=Number(st.losses||0)+1; if(promo){ if(won) advanceTier(st); else { st.promotionReady=false; st.points=Math.max(0,Number(st.points||0)-5); } return; } if(won){ st.points=Number(st.points||0)+25; if(st.points >= (st.tier==='beginner'?50:100)) st.promotionReady=true; } else { st.points=Math.max(0,Number(st.points||0)-10); st.promotionReady=false; } }
  function startCompetitive(){ const p=player(); if(!p?.squad?.length){ toast('먼저 포켓몬을 선택하세요.'); return; } const st=currentTier(); const promo=Boolean(st.promotionReady); const trainer=promo?getPromotionTrainer(st):{name:'경쟁전 AI',team:[],bgm:'battle.mp3'}; const opponentTeam=promo?makeTeam(trainer.team):makeRandomTeam(); const playerTeam=(p.squad||[]).slice(0,3).map(cloneForBattle); PB.battleEngine?.startBattle?.({playerId:'p1',opponentId:'competitive_ai',playerName:p.name,opponentName:trainer.name,playerTeam,opponentTeam,mode:'competitive',theme:st.tier==='beginner'?'beginner':'city',skipLevelReward:true,trainerIntroSrc:'trainer-extra/elitesprite.mp4',specialBgm:trainer.bgm,onComplete:(payload)=>{ const won=payload?.winnerId==='p1'; handleCompetitiveDone(won, promo); setTimeout(()=>{ c()?.returnToLobby?.(); toast(won?'경쟁전 승리':'경쟁전 패배'); }, won?3600:1800); return true; }}); }
  function handleCompetitiveDone(won,promo){ const cc=ensureState(), p=player(); if(!cc||!p) return; if(won){ c()?.addMoney?.('p1',160+tierIndex(currentTier().tier)*60); cc.records.currentWinStreak=Number(cc.records.currentWinStreak||0)+1; cc.records.maxWinStreak=Math.max(Number(cc.records.maxWinStreak||0),Number(cc.records.currentWinStreak||0)); cc.records.competitiveWins=Number(cc.records.competitiveWins||0)+1; cc.mvp.weekWins=Number(cc.mvp.weekWins||0)+1; cc.mvp.monthWins=Number(cc.mvp.monthWins||0)+1; publishMvp(); } else { cc.records.currentWinStreak=0; cc.records.competitiveLosses=Number(cc.records.competitiveLosses||0)+1; } updateTier(won,promo); scanAchievements(); c()?.healPlayerTeam?.('p1'); saveAndPublish(); }
  async function publishMvp(){ const d=db(), k=key(), cc=ensureState(); if(!d||!k||!cc) return; const pub={key:k, nickname:cc.nickname||cc.name||online().nickname||'', characterName:cc.name||player()?.name||'트레이너', tierLabel:tierLabel(currentTier()), title:cc.titles?.equipped||'', wins:Number(cc.mvp.weekWins||0), updatedAt:Date.now()}; try{ await d.ref(`competitive/mvp/week/${currentWeekKey()}/${k}`).set(pub); await d.ref(`competitive/mvp/month/${currentMonthKey()}/${k}`).set({...pub,wins:Number(cc.mvp.monthWins||0)}); }catch(e){} }
  function startMvpChallenge(kind){ const top=Object.entries(F17.mvp[kind==='week'?'week':'month']||{}).sort((a,b)=>Number(b[1].wins||0)-Number(a[1].wins||0))[0]; if(!top){ toast('아직 MVP 스쿼드가 없습니다.'); return; } const topKey=top[0]; const pub=(PB.phase2Online?.players||{})[topKey]; if(!pub?.battleTeam?.length){ toast('MVP 스쿼드 정보를 불러올 수 없습니다.'); return; } const cc=ensureState(); const date=new Date().toISOString().slice(0,10); const challengeKey=`${kind}_${date}`; if(cc.mvp.challenges?.[challengeKey]){ toast('오늘은 이미 승리 보상을 받았습니다.'); return; } const max=highestSquadLevel(); const opponentTeam=pub.battleTeam.slice(0,3).map((d,i)=>{ const base=c()?.state?.pokemonById?.get?.(Number(d.baseId)); const m=c().createRuntimePokemon(base||fallbackBase(), Math.max(1,max-(i?2:0))); if(Array.isArray(d.moves)&&d.moves.length)m.moves=d.moves.slice(0,4).map(x=>({...x})); m.heldItems=Array.isArray(d.heldItems)?d.heldItems.map(x=>({...x})):[]; m.heldItem=m.heldItems[0]||null; return m; }); PB.battleEngine?.startBattle?.({playerId:'p1',opponentId:'mvp_ai',playerName:player()?.name||'나',opponentName:`${kind==='week'?'MoW':'MoM'} ${pub.characterName||'MVP'}`,playerTeam:(player()?.squad||[]).slice(0,3).map(cloneForBattle),opponentTeam,mode:'challenge',theme:'city',skipLevelReward:true,specialBgm:'battle.mp3',onComplete:(payload)=>{ const won=payload?.winnerId==='p1'; if(won){ cc.mvp.challenges=cc.mvp.challenges||{}; cc.mvp.challenges[challengeKey]=true; c()?.addConsumable?.('p1','huge_egg_shard',2); toast('거대알조각 2개 획득'); saveAndPublish(); } c()?.healPlayerTeam?.('p1'); setTimeout(()=>c()?.returnToLobby?.(),2200); return true; }}); }
  function patchCore(){ const core=c(); if(!core||core.__fix17ContentCore) return; core.__fix17ContentCore=true; const oldCreate=core.createRuntimePokemon; core.createRuntimePokemon=function(base,level){ const p=oldCreate.apply(this,arguments); ensureBloodline(p); return p; }; const oldRecalc=core.recalculateRuntimeStats; if(oldRecalc) core.recalculateRuntimeStats=function(p,opts){ const r=oldRecalc.apply(this,arguments); ensureBloodline(p); return r; }; const oldShop=core.getShopCatalog; core.getShopCatalog=function(){ const list=(oldShop?oldShop.apply(this,arguments):(core.state.itemList||[])).concat(core.state.itemList||[]); const seen=new Set(); return list.filter(it=>{ const id=norm(it.id), name=String(it.nameKo||''); if(seen.has(id)) return false; seen.add(id); return id!=='egg_shard' && !/알\s*조각/.test(name); }).map(it=>{ const x={...it}; if(norm(x.id)==='focus_sash'){ x.nameKo='기합의 띠'; x.price=200; x.description='HP가 가득 찬 상태에서 쓰러질 피해를 받으면 한 번 HP 1로 버팁니다.'; x.battleEffect=x.description; } if(norm(x.id)==='black_sludge'){ x.description='독 타입은 매 턴 최대 HP의 1/16을 회복하고, 독 타입이 아니면 매 턴 최대 HP의 1/8 피해를 입습니다.'; x.battleEffect=x.description; } if(norm(x.id)==='huge_egg_shard') x.price=0; return x; }); };
    const oldToggle=core.toggleHeldItem; core.toggleHeldItem=function(uid){ const p=core.getActivePlayer?.()||player(); const selected=norm(core.state.selectedItemId); const item=core.state.itemsById?.get?.(selected); if(item?.category==='기술머신' || selected.startsWith('tm_')){ const mon=[...(p?.squad||[]),...(p?.reserve||[])].find(x=>x.uid===uid); if(mon && Number(mon.level||0)<36){ toast('모든 기술머신은 포켓몬이 36레벨 이상이어야 배울 수 있습니다.'); return; } } return oldToggle?.apply(this,arguments); };
    if(core.state?.itemList && !core.state.itemList.some(it=>norm(it.id)==='huge_egg_shard')) core.state.itemList.push({id:'huge_egg_shard',nameKo:'거대알조각',category:'소비아이템',description:'MoW/MoM 스쿼드 AI 도전 보상 조각입니다.',rank:1,price:0});
    const focus=core.state?.itemList?.find(it=>norm(it.id)==='focus_sash'); if(focus){ focus.nameKo='기합의 띠'; focus.description='HP가 가득 찬 상태에서 쓰러질 피해를 받으면 한 번 HP 1로 버팁니다.'; focus.battleEffect=focus.description; }
    const sludge=core.state?.itemList?.find(it=>norm(it.id)==='black_sludge'); if(sludge){ sludge.description='독 타입은 매 턴 최대 HP의 1/16을 회복하고, 독 타입이 아니면 매 턴 최대 HP의 1/8 피해를 입습니다.'; sludge.battleEffect=sludge.description; }
  }
  function patchRender(){
    if(!PB.league) return;
    const current = PB.league.renderCategory;
    if(current === F17.__renderWrapper) return;
    const old = (current && current !== F17.__renderWrapper) ? current : F17.__baseRenderCategory;
    F17.__baseRenderCategory = old;
    F17.__renderWrapper = function(){
      const tab=PB.phase2Online?.tab || 'ranked';
      if(tab==='achievements') return renderAchievements();
      if(tab==='market') return renderMarket();
      if(tab==='playerMarket') return renderPlayerMarket();
      if(tab==='players') return renderPlayersRanking();
      if(tab==='mow') return renderMvp('week');
      if(tab==='mom') return renderMvp('month');
      let html=old?old.apply(this,arguments):'';
      html=String(html).replace(/<div class="online-tab-row(?:\s+p2-tabs)?">[\s\S]*?<\/div>/, renderTabRow(tab));
      if(!/data-p2-tab=/.test(html)) html = renderTabRow(tab) + html;
      if(tab==='challenge') html=renderChallengeAppend(html);
      return html.replace(/>플레이어</g,'>플레이어 랭킹<').replace(/>랭킹</g,'>포켓몬 랭킹<');
    };
    PB.league.renderCategory = F17.__renderWrapper;
  }
  function decorate(){ try{ updateOwnedHistory(); scanAchievements(); }catch(e){} const p=player(); if(c()?.state?.currentScreen==='lobby'){ const tn=document.getElementById('trainer-name'); const t=ensureState()?.titles?.equipped; if(tn && t && !tn.dataset.f17Title){ tn.dataset.f17Title='1'; tn.innerHTML=`<span class="f17-title-badge">${esc(t)}</span> ${esc(tn.textContent||'')}`; } if(c()?.state?.currentCategory==='squad') decorateSquad(); } }
  function decorateSquad(){ const root=document.getElementById('content-area'); if(!root||root.querySelector('.f17-team-value')) return; const val=teamValue(player()); root.insertAdjacentHTML('afterbegin', `<div class="placeholder-card f17-team-value"><div class="item-title-row"><h3>팀가치</h3><span class="mini-badge">${val.toLocaleString()}원</span></div><p>출전목록 3마리의 시스템마켓 가격 합산 기준입니다.</p></div>`); const overview=root.querySelector('[data-open-overview]'); if(overview && !root.querySelector('[data-f17-blood-tip]')) overview.insertAdjacentHTML('beforebegin', `<button type="button" class="chip-btn" data-f17-blood-tip="1" style="align-self:flex-start;margin-right:6px;">혈통정보</button>`); root.querySelectorAll('.pokemon-card,.reserve-chip').forEach(card=>{ if(card.querySelector('.f17-total-stat')) return; const all=[...(player()?.squad||[]),...(player()?.reserve||[])]; const mon=all.find(m=>(card.textContent||'').includes(monName(m))); if(mon) card.insertAdjacentHTML('beforeend', `<div class="f17-total-stat">총합스탯 ${statTotal(mon.stats?mon:mon.base)}</div>`); }); const h=[...root.querySelectorAll('h3')].find(x=>/강화/.test(x.textContent||'')); if(h) h.textContent='강화-엔드컨텐츠'; }
  function bloodTip(){ openModal('혈통정보 TIP', `<div class="f17-card"><h3>혈통 등급</h3><p>일반혈통 → 우수혈통 → 고대혈통 → 뮤의 후손 순으로 희귀합니다. 포켓몬 획득 시 기존 혈통 확률과 동일하게 랜덤 부여됩니다.</p><p>우수혈통 이상 포켓몬은 +5 강화 성공 시 고대혈통으로 자동 업그레이드되고, +7 강화 성공 시 뮤의 후손으로 자동 업그레이드됩니다.</p><p>강화 비용/확률: 1강 10000원 80%, 2강 15000원 80%, 3강 20000원 80%, 4강 20000원 60%, 5강 25000원 70%, 6강 25000원 20%, 7강 이후 25000원 50%.</p></div>`); }
  function subscribeMvp(){ const d=db(); if(!d||F17.__mvpSub) return; F17.__mvpSub=true; try{ d.ref(`competitive/mvp/week/${currentWeekKey()}`).on('value',s=>{F17.mvp.week=s.val()||{}; ui()?.renderAll?.();}); d.ref(`competitive/mvp/month/${currentMonthKey()}`).on('value',s=>{F17.mvp.month=s.val()||{}; ui()?.renderAll?.();}); }catch(e){} }
  function bind(){ if(F17.__bound) return; F17.__bound=true; document.addEventListener('click', e=>{ const tab=e.target.closest('[data-p2-tab]'); if(tab){ e.preventDefault(); e.stopImmediatePropagation(); if(PB.phase2Online) PB.phase2Online.tab=tab.dataset.p2Tab; const o=online(); if(o && ['ranked','challenge','market'].includes(tab.dataset.p2Tab)) o.view=tab.dataset.p2Tab; patchRender(); ui()?.renderAll?.(); return; } const start=e.target.closest('[data-competitive-start]'); if(start){ e.preventDefault(); e.stopImmediatePropagation(); startCompetitive(); return; }
      const pg=e.target.closest('[data-f17-market-page]'); if(pg){ const all=(c()?.state?.allPokemon||[]).filter(b=>b&&!b.isMegaEvolution); const pages=Math.max(1,Math.ceil(all.length/8)); F17.marketPage=(Number(F17.marketPage||0)+(pg.dataset.f17MarketPage==='next'?1:-1)+pages)%pages; ui()?.renderAll?.(); return; }
      const info=e.target.closest('[data-f17-market-info]'); if(info){ showMarketInfo(info.dataset.f17MarketInfo); return; }
      const comp=e.target.closest('[data-f17-market-compare]'); if(comp){ const id=Number(comp.dataset.f17MarketCompare); F17.compareIds=F17.compareIds.filter(x=>Number(x)!==id); F17.compareIds.push(id); if(F17.compareIds.length>2) F17.compareIds.shift(); if(F17.compareIds.length===2) showCompare(); else toast('비교할 포켓몬 1마리를 더 선택하세요.'); ui()?.renderAll?.(); return; }
      if(e.target.closest('[data-f17-clear-compare]')){ F17.compareIds=[]; ui()?.renderAll?.(); return; }
      const buy=e.target.closest('[data-f17-market-buy]'); if(buy){ buyMarket(buy.dataset.f17MarketBuy); return; }
      const sell=e.target.closest('[data-f17-market-sell]'); if(sell){ sellMarket(sell.dataset.f17MarketSell); return; }
      const eq=e.target.closest('[data-f17-equip-title]'); if(eq){ const cc=ensureState(); cc.titles.equipped=eq.dataset.f17EquipTitle; saveAndPublish(); ui()?.renderAll?.(); return; }
      const sq=e.target.closest('[data-f17-view-squad]'); if(sq){ renderPlayerSquadModal(sq.dataset.f17ViewSquad); return; }
      const inf=e.target.closest('[data-f17-view-info]'); if(inf){ renderPlayerInfoModal(inf.dataset.f17ViewInfo); return; }
      const chal=e.target.closest('[data-f17-mvp-challenge]'); if(chal){ startMvpChallenge(chal.dataset.f17MvpChallenge); return; }
      if(e.target.closest('[data-f17-blood-tip]')){ bloodTip(); return; }
      if(e.target.closest('[data-f17-close-modal]')){ const r=document.getElementById('modal-root'); if(r) r.innerHTML=''; return; }
    }, true); }
  function injectStyle(){ if(document.getElementById('fix17-content-style')) return; const st=document.createElement('style'); st.id='fix17-content-style'; st.textContent=`.f17-avatar{display:inline-flex;align-items:center;justify-content:center;border-radius:999px;overflow:hidden;color:#fff;font-weight:1000;flex:0 0 auto}.f17-avatar img,.f17-avatar video{width:100%;height:100%;object-fit:contain}.f17-type{display:inline-flex;border-radius:999px;padding:2px 7px;margin:0 3px 3px 0;color:#fff;font-size:10px;font-weight:1000}.f17-card{border:1px solid rgba(126,207,255,.26);background:rgba(6,18,34,.45);border-radius:18px;padding:12px;margin:8px 0;color:#fff}.f17-title-row{display:flex;align-items:center;justify-content:space-between;gap:8px}.f17-title-row h3{margin:0}.f17-progress{height:10px;border-radius:999px;background:rgba(255,255,255,.13);overflow:hidden;margin:8px 0}.f17-progress i{display:block;height:100%;background:linear-gradient(90deg,#7ed8ff,#ffd76a)}.f17-title-badge{display:inline-flex;border-radius:999px;padding:2px 7px;background:linear-gradient(135deg,#ffd76a,#7ed8ff);color:#06101f!important;font-size:11px;font-weight:1000;margin-right:4px;text-shadow:none!important}.f17-market-row{grid-template-columns:auto 1fr auto!important}.f17-market-actions{display:flex;flex-direction:column;align-items:flex-end;gap:5px}.f17-modal{max-width:720px!important}.f17-info-head,.f17-compare-head{display:flex;align-items:center;gap:12px;margin-bottom:12px}.f17-compare-head{display:grid;grid-template-columns:1fr 1fr}.f17-compare-head>div{display:flex;align-items:center;gap:8px}.f17-compare-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin:8px 0}.f17-statbox{border:1px solid rgba(255,255,255,.14);border-radius:14px;padding:10px;background:rgba(255,255,255,.06)}.f17-statbox h4{margin:0 0 6px;color:#fff}.f17-stat{display:flex;justify-content:space-between;border-bottom:1px solid rgba(255,255,255,.08);padding:3px 0}.f17-blue{color:#55b8ff!important}.f17-move{border:1px solid rgba(255,255,255,.12);border-radius:12px;padding:8px;margin:6px 0;background:rgba(255,255,255,.06)}.f17-move small{display:block;color:rgba(255,255,255,.72)}.f17-total-stat{margin-top:6px;font-size:12px;font-weight:900;color:#7ed8ff}.online-tab-row.p2-tabs{gap:6px;overflow-x:auto}.online-tab-row.p2-tabs button{white-space:nowrap}`; document.head.appendChild(st); }
  function init(){ if(!PB.core||!PB.ui||!PB.league){ setTimeout(init,100); return; } patchCore(); patchRender(); injectStyle(); bind(); subscribeMvp(); if(!F17.__renderWatchdog){ F17.__renderWatchdog=true; let left=30; const id=setInterval(()=>{ patchRender(); if(--left<=0) clearInterval(id); },300); } const oldRender=PB.ui.renderAll; if(!PB.ui.__fix17ContentRender){ PB.ui.__fix17ContentRender=true; PB.ui.renderAll=function(){ const r=oldRender.apply(this,arguments); setTimeout(()=>{ patchCore(); patchRender(); subscribeMvp(); decorate(); },0); return r; }; } decorate(); if(!F17.__initialPublished){ F17.__initialPublished=true; setTimeout(()=>publishExtra(),850); } }
  document.addEventListener('DOMContentLoaded',()=>setTimeout(init,520)); setTimeout(init,900);
})();
