
(function(){
  'use strict';
  const PB = window.POKEBATTLE || (window.POKEBATTLE = {});
  const V = PB.phase2ContentV2 = PB.phase2ContentV2 || { endLocked:false, allowExit:false, restTimer:null };
  const esc = (v)=>String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const norm = (v)=>String(v||'').toLowerCase().replace(/[^a-z0-9_가-힣]/g,'');
  const now = ()=>Date.now();
  function core(){return PB.core;} function ui(){return PB.ui;} function online(){return PB.online||{};} function db(){return online().db||null;} function uid(){return online().uid||null;} function slot(){return online().selectedSlot||'char1';} function key(){return uid()?`${uid()}_${slot()}`:'';} function char(){return online().selectedCharacter||null;} function player(){return core()?.getPlayer?.('p1')||core()?.getActivePlayer?.()||null;} function toast(m){ui()?.showToast?.(m);} 
  const BL = {normal:['일반혈통','#c9ced8','#06101f'], elite:['우수혈통','#62c9ff','#06101f'], ancient:['고대혈통','#ffd85d','#171100'], mew:['뮤의 후손','#bd79ff','#06101f']};
  function bkey(v){ const s=String(v||'normal'); if(s.includes('뮤')||s==='mew')return 'mew'; if(s.includes('고대')||s==='ancient')return 'ancient'; if(s.includes('우수')||s==='elite'||s==='superior')return 'elite'; return 'normal'; }
  function pname(p){ return p?.currentName||p?.name||p?.base?.nameKo||p?.nameKo||'포켓몬'; }
  function ensureExtraItems(){
    const c=core(); if(!c?.state?.itemList || c.__contentV2Items) return; c.__contentV2Items=true;
    const add=(item)=>{ const id=norm(item.id); if(c.state.itemsById?.has(id)) { Object.assign(c.state.itemsById.get(id), item); return; } c.state.itemList.push(item); c.state.itemsById?.set(id,item); };
    add({id:'heart_scale',nameKo:'하트비늘',nameEn:'Heart Scale',category:'소비아이템',rank:92,price:180,description:'포켓몬이 잊은 기술을 다시 배우게 합니다.',battleEffect:'가방에서 포켓몬에게 사용합니다.',colorA:'#ff9fc4'});
    add({id:'huge_egg_shard',nameKo:'거대알 조각',nameEn:'Huge Egg Shard',category:'재료',rank:94,price:0,description:'10개를 모으면 거대알로 교환할 수 있습니다.',colorA:'#9d69ff'});
    const palk=c.state.itemsById.get('palkia_pearl'); if(palk) palk.nameKo='백옥';
    const dia=c.state.itemsById.get('dialga_diamond'); if(dia) dia.nameKo='금강석';
  }
  function patchCore(){ const c=core(); if(!c||c.__contentV2Core) return; c.__contentV2Core=true; ensureExtraItems();
    const oldShop=c.getShopCatalog; c.getShopCatalog=function(){ ensureExtraItems(); let list=(oldShop?oldShop.call(this):[]).map(it=>({...it}));
      const blocked=new Set(['mythic_fragment','artisan_knowledge','groudon_skeleton','palkia_pearl','kyogre_heart','dialga_diamond','awakening_lance','fighting_serum','hunting_instinct','storm_claw','unyielding_armor','golden_starlight','infinite_growth_drug','swift_boots','tri_relic_fragment','sealing_chain']);
      list=list.filter(it=>!blocked.has(norm(it.id)) && !/신화의\s*파편|장인의\s*지식/.test(String(it.nameKo||'')));
      const has=(id)=>list.some(it=>norm(it.id)===id);
      if(!has('heart_scale')) list.push(c.state.itemsById.get('heart_scale'));
      list=list.filter(Boolean).map(it=>{ const id=norm(it.id); if(id==='rare_candy') it.price=500; if(id==='focus_sash') it.price=300; if(/^tm_/.test(id)) it.price=Number(it.price||1000); return it; });
      const first=['rare_candy','good_potion','revive_shard','recovery_potion']; const egg=['mystery_egg','huge_egg','special_egg']; const status=['paralyze_heal','antidote','burn_heal','ice_heal','awakening_spray','pp_aid','pp_aide'];
      const rank=(it)=>{ const id=norm(it.id); if(first.includes(id))return [0,first.indexOf(id)]; if(egg.includes(id))return [1,egg.indexOf(id)]; if(/^tm_/.test(id))return [2,-Number(it.price||0)]; if(status.includes(id))return [9,status.indexOf(id)]; return [4,Number(it.rank||999)]; };
      return list.sort((a,b)=>{ const A=rank(a),B=rank(b); return A[0]-B[0]||A[1]-B[1]||String(a.nameKo||'').localeCompare(String(b.nameKo||''),'ko'); }); };
    const oldBuy=c.buyShopItem; c.buyShopItem=function(pid,itemId){ ensureExtraItems(); return oldBuy.call(this,pid,itemId); };
    const oldSelect=c.selectItem; c.selectItem=function(itemId){ const id=norm(itemId); const p=player(); if(id==='egg_shard'||id==='huge_egg_shard'){ const entry=(p?.bag?.consumables||[]).find(x=>norm(x.id)===id); if(entry && Number(entry.amount||0)>=10){ entry.amount-=10; c.addConsumable('p1', id==='egg_shard'?'mystery_egg':'huge_egg', 1); toast(id==='egg_shard'?'알로 교환했습니다.':'거대알로 교환했습니다.'); ui()?.renderAll?.(); return; } } return oldSelect.apply(this,arguments); };
    const oldToggle=c.toggleHeldItem; c.toggleHeldItem=function(uidValue){ const selected=norm(c.state.selectedItemId); if(selected==='heart_scale'){ useHeartScale(uidValue); return; } return oldToggle.apply(this,arguments); };
    const oldCreate=c.createRuntimePokemon; c.createRuntimePokemon=function(base,level){ const p=oldCreate.call(this,base,level); p.originalName=p.originalName||base?.nameKo||p.currentName; return p; };
  }
  function useHeartScale(uidValue){ const p=[...(player()?.squad||[]),...(player()?.reserve||[])].find(x=>x.uid===uidValue); if(!p) return; const bag=player().bag.consumables||[]; const hs=bag.find(x=>norm(x.id)==='heart_scale'); if(!hs||Number(hs.amount||0)<=0){toast('하트비늘이 없습니다.');return;} const cur=new Set((p.moves||[]).map(m=>m.nameKo||m.name)); const old=(p.base?.moves||[]).filter(m=>!cur.has(m.nameKo||m.name)); if(!old.length){toast('다시 배울 기술이 없습니다.');return;} const root=document.getElementById('modal-root'); root.innerHTML=`<div class="overlay"><div class="modal-card p2-modal"><div class="modal-header"><h2>기술 되살리기</h2><button class="close-btn" data-p2fp-close-modal="1">✕</button></div><div class="modal-body"><p>${esc(pname(p))}이(가) 다시 배울 기술을 선택하세요. 기술이 4개면 마지막 기술을 대체합니다.</p>${old.map((m,i)=>`<button class="p2-btn" data-relearn-move="${i}">${esc(m.nameKo||m.name)} <small>${esc(m.type||'')} · 위력 ${esc(m.power||'-')}</small></button>`).join('')}<button class="p2-btn alt" data-p2fp-close-modal="1">사용취소</button></div></div></div>`; root.onclick=(e)=>{ const b=e.target.closest('[data-relearn-move]'); if(!b)return; const m={...old[Number(b.dataset.relearnMove)]}; if((p.moves||[]).length>=4)p.moves[p.moves.length-1]=m; else {p.moves=p.moves||[]; p.moves.push(m);} hs.amount-=1; root.innerHTML=''; ui()?.renderAll?.(); toast(`${m.nameKo||m.name}을 다시 배웠습니다.`); }; }
  function patchBattleEnd(){ /* fix15 disabled old end wrapper */ return;  const be=PB.battleEngine; const c=core(); if(be&&!be.__contentV2StartWrap){ be.__contentV2StartWrap=true; const old=be.startBattle; be.startBattle=function(opts={}){ const orig=opts.onComplete; opts={...opts,onComplete:(payload)=>{ let handled=false; try{ handled=orig?orig(payload):false; }catch(e){console.warn(e);} showEndStats(payload); V.endLocked=true; V.allowExit=false; return true; }}; return old.call(this,opts); }; } if(c&&!c.__contentV2ReturnGuard){ c.__contentV2ReturnGuard=true; const oldRet=c.returnToLobby; c.returnToLobby=function(){ if(V.endLocked&&!V.allowExit){showEndStats(); return;} return oldRet.apply(this,arguments); }; const oldSet=c.setCategory; c.setCategory=function(){ if(V.endLocked&&!V.allowExit){showEndStats(); return;} return oldSet.apply(this,arguments); }; } if(ui()&&!ui().__contentV2RenderGuard){ ui().__contentV2RenderGuard=true; const old=ui().renderAll; ui().renderAll=function(){ if(V.endLocked&&!V.allowExit&&core()?.state?.currentScreen==='lobby'){ core().state.currentScreen='battle'; } const r=old.apply(this,arguments); setTimeout(decorate,0); return r; }; } }
  function showEndStats(payload){ const grid=document.getElementById('battle-action-grid'); if(!grid)return; const stats=payload?.stats||PB.battleEngine?.getSnapshot?.()?.stats||{}; const rows=Object.values(stats).map(s=>`<tr><td>${esc(s.name||s.pokemonName||'포켓몬')}</td><td>${Number(s.damageDealt||0)}</td><td>${Number(s.survivedDamage||s.damageTaken||0)}</td></tr>`).join('')||'<tr><td colspan="3">통계 없음</td></tr>'; grid.innerHTML=`<div class="v2-endstats"><h3>배틀 통계</h3><table><tr><th>포켓몬</th><th>딜량</th><th>버틴피해</th></tr>${rows}</table><button class="action-button" data-content-v2-exit="1"><span class="action-title">나가기</span><span class="action-sub">로비로 돌아갑니다.</span></button></div>`; }
  function renamePokemon(uidValue){ const mon=[...(player()?.squad||[]),...(player()?.reserve||[])].find(p=>p.uid===uidValue); if(!mon)return; const old=pname(mon); const name=(prompt('포켓몬 이름을 입력하세요', old)||'').trim().slice(0,10); if(!name)return; mon.originalName=mon.originalName||mon.base?.nameKo||old; mon.currentName=name; ui()?.renderAll?.(); window.PB_ONLINE_V3?.saveCharacter?.(); publishPublicNames(); }
  async function publishPublicNames(){ try{ if(!db()||!key())return; const team=(player()?.squad||[]).slice(0,3).map(p=>({uid:p.uid,baseId:p.base?.id,name:pname(p),originalName:p.originalName||p.base?.nameKo||'',level:p.level,bloodline:p.bloodline,heldItems:p.heldItems||[],moves:p.moves||[],types:p.currentTypes||p.base?.type||[]})); await db().ref(`playerPublicList/${key()}`).update({mainPokemon:team[0]||null,squad:team,battleTeam:team,updatedAt:now()}); }catch(e){console.warn(e);} }
  function decorate(){ ensureExtraItems(); document.querySelectorAll('.bloodline-text-v3,.battle-bloodline-v3,.p2-blood,.rt-blood,.blood-block,.v7-blood-block,.p2fp-blood-fixed').forEach(el=>{ const k=bkey(el.textContent); el.textContent=BL[k][0]; el.style.setProperty('background',BL[k][1],'important'); el.style.setProperty('color',BL[k][2],'important'); el.style.setProperty('-webkit-text-fill-color',BL[k][2],'important'); el.style.setProperty('box-shadow','none','important'); el.style.setProperty('text-shadow','none','important'); el.style.setProperty('animation','none','important'); }); document.querySelectorAll('.pokemon-card[data-select-uid]').forEach(card=>{ if(!card.querySelector('.rename-pokemon-btn')){ const line=card.querySelector('.name-line'); const uid=card.dataset.selectUid; if(line) line.insertAdjacentHTML('beforeend',`<button type="button" class="rename-pokemon-btn" data-rename-pokemon="${esc(uid)}">✏️</button>`); } }); const moneyLabels=[...document.querySelectorAll('h1,h2,h3,span,b,div')].filter(n=>/^보유 재화\s*:?$/.test((n.textContent||'').trim())); moneyLabels.forEach(n=>n.style.setProperty('color','#ffd84f','important')); document.querySelectorAll('.shop-item-card .item-title-row h3,.shop-item-card h3').forEach(n=>n.style.setProperty('color','#fff','important')); document.querySelectorAll('.shop-price,.shop-item-card .mini-badge').forEach(n=>{ n.style.setProperty('background','#ffd84f','important'); n.style.setProperty('color','#06101f','important'); n.style.setProperty('-webkit-text-fill-color','#06101f','important'); }); document.querySelectorAll('.shop-item-card').forEach(card=>{ card.innerHTML=card.innerHTML.replace(/기술머신[:：]\s*/g,''); }); document.querySelectorAll('.shop-item-card p,.tm-detail-modal p').forEach(p=>{p.innerHTML=p.innerHTML.replace(/위력\s*(\d+)/g,'<span class="power-yellow">위력 $1</span>');}); document.querySelectorAll('p,small,span,div').forEach(n=>{ if(n.childElementCount===0 && (n.textContent||'').includes('알 조각 10개로 알 교환')) n.textContent='알 조각으로 교환, 파편과 지식으로 희귀 지닌물건을 랜덤 제작합니다'; if((n.textContent||'').includes('보유 재화')){ const html=n.innerHTML; if(!html.includes('money-label-yellow')) n.innerHTML=html.replace('보유 재화','<span class="money-label-yellow">보유 재화</span>'); } }); }
  function renderRestArea(){ const root=document.querySelector('.content-scroll')||document.querySelector('#lobby-content')||document.querySelector('.lobby-screen'); if(!root)return; const main=(player()?.squad||[])[0]; const sprite=main?.base?.image||main?.base?.sprite||''; root.innerHTML=`<section class="rest-area"><button class="rest-exit" data-rest-exit="1">나가기</button><img src="grass.gif" class="rest-grass"><div class="rest-pokemon-slot"></div></section>`; const slot=root.querySelector('.rest-pokemon-slot'); clearInterval(V.restTimer); const spawn=()=>{ if(!slot)return; const x=20+Math.random()*45; const y=10+Math.random()*38; slot.innerHTML=sprite?`<img src="${esc(sprite)}" style="left:${x}%;bottom:${y}%;">`:`<span style="left:${x}%;bottom:${y}%;">${esc(String(pname(main)).slice(0,1))}</span>`; setTimeout(()=>{ if(slot)slot.innerHTML='';},2100); }; spawn(); V.restTimer=setInterval(spawn,3000); }
  function patchCompetitiveView(){ const old=PB.league?.renderCategory; if(!old||PB.league.__contentV2Rest) return; PB.league.__contentV2Rest=true; PB.league.renderCategory=function(){ let html=old.apply(this,arguments); if(window.POKEBATTLE?.phase2Online){ html=String(html).replace('<button data-p2-tab="rankings"','<button data-p2-tab="rest"').replace('>랭킹</button>','>쉼터</button><button data-p2-tab="rankings" class="">랭킹</button>'); } return html; }; document.addEventListener('click',e=>{ const t=e.target.closest('[data-p2-tab="rest"]'); if(t){ e.preventDefault(); e.stopImmediatePropagation(); if(PB.phase2Online) PB.phase2Online.tab='rest'; renderRestArea(); } const x=e.target.closest('[data-rest-exit]'); if(x){ e.preventDefault(); clearInterval(V.restTimer); if(PB.phase2Online) PB.phase2Online.tab='ranked'; ui()?.renderAll?.(); }} ,true); }
  function installCss(){ if(document.getElementById('content-v2-style'))return; const st=document.createElement('style'); st.id='content-v2-style'; st.textContent=`
    .rename-pokemon-btn{margin-left:6px;border:1px solid rgba(255,255,255,.28);border-radius:999px;background:rgba(255,255,255,.15);padding:2px 6px;font-size:12px;position:relative;z-index:5}.v2-endstats{width:100%;background:rgba(255,255,255,.94);color:#06101f;border-radius:18px;padding:12px}.v2-endstats *{color:#06101f!important}.v2-endstats table{width:100%;border-collapse:collapse}.v2-endstats td,.v2-endstats th{padding:5px;border-bottom:1px solid rgba(0,0,0,.12);text-align:left}.power-yellow{color:#ffd84f!important;font-weight:1000}.money-label-yellow{color:#ffd84f!important;-webkit-text-fill-color:#ffd84f!important;font-weight:1000}.tm-detail-modal,.tm-detail-modal .modal-body{background:#05070d!important;color:#fff!important}.tm-detail-modal *{color:#fff!important}.rest-area{position:relative;height:calc(100dvh - 130px);min-height:560px;margin:-8px;border-radius:28px;overflow:hidden;background:linear-gradient(180deg,rgba(5,20,12,.35),rgba(0,0,0,.15)),url('pokebackground.png') center/cover no-repeat}.rest-exit{position:absolute;right:14px;top:14px;z-index:5;border-radius:999px;background:rgba(0,0,0,.58);color:#fff;border:1px solid rgba(255,255,255,.35);padding:9px 14px;font-weight:1000}.rest-grass{position:absolute;right:10px;bottom:20px;width:min(46vw,240px);height:auto;z-index:2}.rest-pokemon-slot img,.rest-pokemon-slot span{position:absolute;z-index:3;max-width:76px;max-height:76px;animation:restWiggle 2s ease-in-out forwards;transform-origin:50% 100%}.rest-pokemon-slot span{display:flex;width:64px;height:64px;border-radius:50%;background:#ffd84f;color:#06101f;align-items:center;justify-content:center;font-weight:1000}@keyframes restWiggle{0%{opacity:0;transform:translateY(12px) rotate(0deg)}18%{opacity:1;transform:translateY(0) rotate(-28deg)}42%{transform:rotate(26deg)}65%{transform:rotate(-18deg)}100%{opacity:0;transform:translateY(8px) rotate(0deg)}}.shop-item-card .mini-badge,.shop-price{border-radius:999px!important;padding:4px 9px!important}.p2-room .p2-btn[data-p2-room-start]{display:inline-flex!important}.p2fp-wait .p2-btn,.pvp-ready-wait .p2-btn{margin-top:8px}.bloodline-text-v3,.battle-bloodline-v3,.p2-blood,.rt-blood,.blood-block,.v7-blood-block,.p2fp-blood-fixed{transition:none!important;animation:none!important;box-shadow:none!important;text-shadow:none!important;}
  `; document.head.appendChild(st); }
  function bind(){ document.addEventListener('click',async e=>{ const rn=e.target.closest('[data-rename-pokemon]'); if(rn){e.preventDefault(); e.stopImmediatePropagation(); renamePokemon(rn.dataset.renamePokemon); return;} const ex=e.target.closest('[data-content-v2-exit]'); if(ex){ V.allowExit=true; V.endLocked=false; core().state.currentScreen='lobby'; ui()?.renderAll?.(); return;} const waitExit=e.target.closest('[data-pvp-wait-exit]'); if(waitExit){ e.preventDefault(); V.allowExit=true; V.endLocked=false; try{ await db()?.ref(`battleRooms/${waitExit.dataset.pvpWaitExit}`).update({status:'cancelled',cancelledBy:key(),updatedAt:now()}); }catch(err){} core().state.currentScreen='lobby'; ui()?.renderAll?.(); return;} },true); }
  function patchWaitMessage(){ const fs=PB.phase2FinalStability; // handled by DOM rewrite interval below
    setInterval(()=>{ const wait=document.querySelector('.pvp-ready-wait.big,.pvp-ready-wait'); if(wait && !wait.querySelector('[data-pvp-wait-exit]') && (PB.phase2FinalStability?.roomId)){ wait.insertAdjacentHTML('beforeend',`<br><button class="p2-btn alt" data-pvp-wait-exit="${esc(PB.phase2FinalStability.roomId)}">나가기</button>`); } },500); }
  function init(){ if(!core()||!ui()){setTimeout(init,120);return;} installCss(); patchCore(); patchBattleEnd(); patchCompetitiveView(); bind(); patchWaitMessage(); /* v8: recurring decorate disabled */ setTimeout(decorate,200); }
  document.addEventListener('DOMContentLoaded',()=>setTimeout(init,1200));
})();
